### ISSUE TITLE
Configure triggers

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#109]
Figure out a good way to include triggers in the deploy process and implement it.

**Comment by eouthwaite** [comment]
Could Richard's method be implemented as standard ?
https://rclayton.silvrback.com/writing-and-deploying-triggers-in-marklogic-roxy

**Comment by grtjn** [comment]
I would prefer going even a step further, and taking deployment of CPF as example:

```
ml local deploy triggers
ml local clean triggers
```

and while at it:

```
ml local deploy alerts
ml local clean alerts
```

The idea would be to record essential settings in some XML config, and have that interpreted and executed. The syntax could be close to the real XML syntax of triggers/alerts inside the database. I expect that to be less error prone..

**Comment by dmcassel** [comment]
+1 on adding commands for triggers and alerts

**Comment by peetkes** [comment]
At last!!! +1!

**Comment by grtjn** [comment]
Sorry guys, pushing away for the time being..

**Comment by dmcassel** [comment]
@adamfowleruk @peetkes @eouthwaite I implemented deploying and removing (cleaning) triggers. Testers welcome.

**Comment by dmcassel** [comment]
If this approach looks good, alerts could be added to the same file (triggers-config.xml) or to a file that is specific to alerts.

**Comment by dmcassel** [comment]
Added a [wiki](https://github.com/marklogic/roxy/wiki/Triggers) describing the new feature (currently in a PR).

**Comment by dmcassel** [comment]
fixed in dev
