### ISSUE TITLE
Use an existing database and its forests

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#114]
If you specify the content-db property and point to an existing database, Roxy will successfully use that database with the app servers. However, if the forests don't match Roxy's naming convention, it will create new ones and attach them, in addition to the forests that were already there. 

Add a property called external-content-db={true,false}. Default is false. If set to true:
- bootstrapping will expect to find a database with the name indicated by the content-db property. Bootstrapping will fail if this database does not exist. 
- bootstrapping will not attach, detach, or otherwise mess with the forests attached to the database. 
- bootstrapping will still apply other configuration changes to the content database. 
- wipe will not remove the database or its forests.

**Comment by grtjn** [comment]
No need to hard-code content-db name in ml-config. Just update build.properties, along with deleting the database section from ml-config. See also https://github.com/marklogic/roxy/wiki/Using-an-existing-Content-Database
