### ISSUE TITLE
Need to restart for collation changes to server

### ISSUE THREAD

**Issue by mustard57** [marklogic/roxy#125]
I've found that if I change server collation in ml-config.xml I need to do a restart for it to be effective. However, if I do this directly in the admin console I do not. The best way to test is to put a simple module in place like 

xdmp:set-response-content-type("text/html"),
"Checking comparisons ...",
"A" = "a"

and then toggle your collation to case sensitive and back via the collation field in ml-config.xml and ml local bootstrap and see whether the boolean returned from the above changes. For ease of reference ...

http://marklogic.com/collation//S1 - case insensitive

http://marklogic.com/collation/codepoint - case sensitive

**Comment by grtjn** [comment]
I think this is more an issue in MarkLogic itself. If restart is required, the admin save-config(-without-restart) function should respond accordingly. We rely on how these functions behave.

I also tested against latest ML, and no longer observed the issue. The collation was changed just fine..

Closing as won't fix..

**Comment by mustard57** [comment]
Sounds good to me. Cheers.
