### ISSUE TITLE
Better error message for missing role

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#131]
When I am hacking on the role configuration, sometimes I mistype a role name and a role therefore does not exist for userB, .. In this circumstance Roxy will create the mistyped role, and error that the role does not exist for B.

A better error message for missing roles etc would be good.

**Comment by grtjn** [comment]
Not sure what the feedback used to be, but I just ran a test, and I got:

```
$ ./ml ml9 bootstrap
Bootstrapping your project into MarkLogic 9 on ml9-ml1...
ERROR: SEC-ROLEDNE: (err:FOER0000) Role does not exist: sec:role-name = roxy-rolex
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED
```
Seems okay to me.
