### ISSUE TITLE
Create a package manager for REST API extensions and transforms

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#133]
Analogous to [npm](https://npmjs.org/). 

Motivation: make it easy to share REST API service extensions and transformations. 

`$ ml pm install tagger`
- downloads the tagger extension, puts it into the rest/ext directory of the current Roxy project. 
- downloads any dependent libraries, sets up the path under your src directory. Convention: src/lib/{extension-name}/{libraries}. _enforced?_
- downloading happens by "git clone" to a tmp directory, then files are moved to the appropriate locations. 
- stores information about what was installed. _where?_

`$ ml pm remove tagger`
- lists files to be removed from the current Roxy project, prompts to confirm

`$ ml pm publish tagger.xml`
- sends tagger.xml to package registry (a public-facing web site hosted by MarkLogic registry.marklogic.com). 

```
<package>
  <extension>
    <name>tagger</name>
    <location>http://github.com/dmcassel/tagger</location>
    <description>Takes parameters "uri", "tag", and "path". Inserts a &amp;lt;tag&amp;gt; element with the value of the tag parameter at the specified path.<description>
    <works-with-ml>6</works-with-ml>
    <license url="http://opensource.org/licenses/MIT">MIT</license>
  </extension>
</package>
```

```
<package>
  <transform>
    <name>flatten-meta</name>
    <location>http://github.com/dmcassel/flatten-meta</location>
    <description>Converts elements of the form &amp;amp;lt;meta name="foo" value="bar"/&amp;gt; to &amp;lt;foo&amp;gt;bar&amp;lt;/foo&amp;gt;</description>
    <works-with-ml>6</works-with-ml>
    <works-with-ml>7</works-with-ml>
    <license url="http://opensource.org/licenses/MIT">MIT</license>
  </transform>
</package>
```

registry.marklogic.com would provide services to the "ml pm" command and allow for package browsing, like https://npmjs.org/.  

This ticket lists first-cut functionality.

**Comment by grtjn** [comment]
[MLPM](https://github.com/joemfb/mlpm) saw light in 2015, and covers the needs described here. It comes with it's own mechanism to deploy src, as well as extensions, but that can be integrated into Roxy without too much difficulty. However, that is covered in #357.

I think there is no need for another package manager..
