### ISSUE TITLE
load command's --remove-prefix doesn't work on windows

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#144]
On Windows, ml load is keeping the full path (C:\...), even if backslashes are escaped (\\) or if the path is quoted.

**Comment by grtjn** [comment]
Given the age of this ticket, and the trouble to reproduce this, I vote to close this ticket.

**Comment by rlouapre** [comment]
I frequently use ```ml load``` in Windows with no issues. I convert all ```\``` in ```/``` in ```path``` and ```--remove-prefix```.
