### ISSUE TITLE
Modify default security settings to allow for rest-reader

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#145]
It should be easy for a rest-based app to get security set up such that the app-user can access the application. Add the appropriate roles when creating a hybrid or rest application. 

Implementation note: include the needed roles in the ml-config.sample.xml, in XML comments. When initializing for --app-type=rest or --app-type=hybrid, remove the comment markers.

**Comment by RobertSzkutak** [comment]
@dmcassel I believe this is currently supported and able to be closed. Agree?

**Comment by dmcassel** [comment]
It's in the dev branch, so it will be in master soon. Agree to close.
