### ISSUE TITLE
Need to use admin index creation function when creating indexes

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#161]
Right now we are passing in the index xml directly from ml-config.xml into the admin API functions to create indexes:

```
declare function setup:add-range-element-attribute-indexes-R(
  $admin-config as element(configuration),
  $database as xs:unsignedLong,
  $index-configs as element(db:range-element-attribute-index)*) as element(configuration)
{
  if ($index-configs) then
    setup:add-range-element-attribute-indexes-R(
      admin:database-add-range-element-attribute-index($admin-config, $database, $index-configs[1]),
      $database,
      fn:subsequence($index-configs, 2))
  else
    $admin-config
};
```

Instead, we need to use the appropriate admin API function to create the index xml prior to calling the create function(s):

```
admin:database-range-element-attribute-index(...)
```

This keeps dirty xml from making its way into the server xml configs. If dirty xml gets in there then bad things happen.

**Comment by grtjn** [comment]
This looks fixed, in dev and master..
