### ISSUE TITLE
Roxy incorrectly rewrites REST http 500 response content type in hybrid application

### ISSUE THREAD

**Issue by adamfowleruk** [marklogic/roxy#162]
I had reported a bug against MarkLogic 24847 because a HTTP 500 returns a content type of text/plain which outfoxed MLJS. Turns out this only occurs on Roxy Hybrid apps wrapping the REST server, not on REST only apps:-

curl --verbose --user admin --anyauth "http://localhost:8120/v1/search?structuredQuery={}&format=json&options=flibblewibble"

Execute the above against a pure REST app and you get a content type of application/xml (correctly)
Execute it against a Roxy hybrid app and you get text/plain (incorrect)

I have a workaround in MLJS, but others may be foxed by this.

**Comment by grtjn** [comment]
Adam is right. The Roxy error handler doesn't take REST exceptions into account sufficiently. It only identifies RESTAPI-EXTNERR. Things would improve if it extends that to `fn:starts-with($ex/error:code, "REST")`.

**Comment by grtjn** [comment]
Fixed in dev
