### ISSUE TITLE
Better error message when an extra app-server refers to a project database

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#166]
1. Bootstrap a project
2. Create another app server that refers to the content (or modules) database (eg., run app builder, or manually set up some other app server)
3. Wipe the project

The error message that results is a big stack trace. The essential message is contained in the trace:

"The following http-servers still refer to this database: " followed by the name(s). Reduce the error output to just that message.

**Comment by grtjn** [comment]
I ran a check with latest Roxy, and got returned:

```
Wiping MarkLogic setup for your project from ml9-ml1...
ERROR: ADMIN-DATABASEINUSE: (err:FOER0000) The following http-servers still refer to this database: test.
See MarkLogic Server error log for more details.
ERROR: ... Wipe FAILED
```

Not perfect, but seems okay to me.
