### ISSUE TITLE
separate deploy modules from rest extensions and transforms

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#231]
Is it an idea to add extra commands for deployment of the src folder (only the website and libraries if any), deployment of rest extensions and deployment of custom transforms?
So when you do deploy modules it will deploy everything
deploy rest will deploy only the rest extensions, with an extra option to just deploy a single extension if you specify the name of the extension and deploy transform will deploy only the transforms , with an extra option to just deploy a single transform when you specify the name of the transform.

**Comment by grtjn** [comment]
Fixed in dev (and master?)
