### ISSUE TITLE
File include for ml-config.xml

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#235]
Does Roxy support file include for ml-config.xml?

**Comment by grtjn** [comment]
I'd leave getting it from remote to the end users responsibility. There are plenty ways to make sure shared code can be pulled in, for instance using git(hub) submodules.

I'd also like to point to the fact Roxy supports a comma-separated list in the `config.file` property. Next to that, it also supports so-called `shared_config` these days: https://github.com/marklogic/roxy/blob/516507b4eb047d0a35a2769d0422fa3cf5a9a978/deploy/sample/build.sample.properties#L29. I think if you combine the two, you can potentially achieve what was looked for here.

I vote closing this ticket. All agree?
