### ISSUE TITLE
Shared role on wipe command

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#242]
On `ml wipe` command, I believe Roxy does not check if a role defined in ml-config.xml has been assigned to a user _not managed by Roxy script_.
- Am I correct?
- Would it make sense to keep the role in that scenario?

**Comment by grtjn** [comment]
I think this ticket is outdated. ML 7+ sec:remove-role seems to already take care of this. The external user remains, but the role disappears from the list of inherited roles. Doesn't even show up in xdmp:user-roles.
