### ISSUE TITLE
Reusing existing content db (or other db's?)

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#245]
If you point from two Roxy project to a shared content db, both will try to create, update, and delete that content db. You can trick one project by added a custom property, for instance shared-content-db, point to that in ml-config.xml for the http-server settings, and remove the content-db part entirely, but a small flag alike install-xcc=false might be more convenient..

One might also have a good reason to want to share a modules-db. A similar thing would account there. How about some extra flags:
- install-modules-db=false
- install-content-db=false

Maybe more?

**Comment by grtjn** [comment]
Yet slightly different approach would be to add a `shared="true"` parameter inside ml-config.xml. It would make it get created at bootstrap (only if missing), and skipped on wipe. An extra param `--wipe-shared` would force wiping shared stuff..

**Comment by grtjn** [comment]
You can already get there partly, by specifying a content-db name that already exists, and then removing database + assignments for that database from ml-config. It won't get created, won't get wiped. It must exist upfront..

**Comment by dmcassel** [comment]
Would it be sufficient to document the "removing the database assignments" approach, perhaps on the [Database Configuration wiki](https://github.com/marklogic/roxy/wiki/Database-Configuration)?

**Comment by grtjn** [comment]
I like the idea of having that shared=true flag in ml-config. It sounds versatile, and should be relatively easy to implement. But a section on that wiki sounds like a good idea too, and perhaps quickest to provide..

**Comment by grtjn** [comment]
Looking back over this and related tickets my current thinking is not in favor of having configs or flags that tell Roxy something is shared. The reason is that I think it would be confusing if the content-db section is still within ml-config, despite it not doing much, or maybe nothing at all. A shared=true flag can be overlooked easily, but if the content-db section is completely removed, no confusion about whether that project creates/configures the db or not..

I opened this wiki to document the approach in more detail: https://github.com/marklogic/roxy/wiki/Using-an-existing-Content-Database

Same principle should also work for the other db's..
