### ISSUE TITLE
test command crashes if no triggers database is defined

### ISSUE THREAD

**Issue by michaelgursky** [marklogic/roxy#254]
If there is no triggers database defined, "ml \<env\> test" crashes with an XDMP-NODB error, making it difficult to integrate into a CI build.  It would be good if this were caught in the xquery code and returned in a different manner.  It seems the testing UI turns this into a "NO TESTS RUN" message.

**Comment by grtjn** [comment]
I think it should be pretty easy to test if ml.triggers-db is empty, but how should the system respond? It could skip the CPF related tests silently. Depends what purpose those CPF tests really serve I guess, not sure I know them well enough to judge. Moreover, the UI should ignore it too. That is not ignoring it silently, but failing (red border) with no particular message..

**Comment by grtjn** [comment]
Fixed in dev
