### ISSUE TITLE
issues with Amazon load balancer

### ISSUE THREAD

**Issue by michaelgursky** [marklogic/roxy#255]
(Just noting for the record, not necessarily requesting any changes.)

I was recently testing roxy with an AWS cluster set up using the ELB (elastic load balancer).  I ran into a couple of issues:
1. Roxy sends a version name of "XDBC/1.0" in the HTTP request line.  This causes the load balancer to reject the request with 400: Bad request.  Changing this (in write_header in xcc.rb) to "HTTP/1.1" fixes the problem.
2.  "deploy modules" with the batch setting on (the default), results in 504: Gateway timeout.  The fix is to use "deploy modules --batch=false" so that each module is committed individually.

**Comment by bakkenh** [comment]
In case someone runs across this on a google search, the best solution is covered here:

https://github.com/marklogic/roxy/wiki/Using-Roxy-Deployer-with-Amazon

I had this same issue- the fix was to change the listener to accept TCP instead of HTTP on the XCC port.

**Comment by dmcassel** [comment]
Thanks @bakkenh. If you've got more details that we can put on that wiki, I'd be happy to add them.

**Comment by grtjn** [comment]
Added details about 504 timeout to the wiki..
