### ISSUE TITLE
deploy content fails with non-ASCII file names on Windows

### ISSUE THREAD

**Issue by fsnow** [marklogic/roxy#256]
With file "EntitéGénérique.xml" in my data directory, I get the following error. Paxton tested on Mac and did not get an error.

```
ERROR: 500 "Internal Server Error"
ERROR: <error:error xsi:schemaLocation="http://marklogic.com/xdmp/error error.xsd" xmlns:error="http
://marklogic.com/xdmp/error" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <error:code>XDMP-URI</error:code>
  <error:name/>
  <error:xquery-version>1.0-ml</error:xquery-version>
  <error:message>Invalid URI format</error:message>
  <error:format-string>XDMP-URI: Invalid URI format: ""</error:format-string>
  <error:retryable>false</error:retryable>
  <error:expr/>
  <error:data>
    <error:datum>""</error:datum>
  </error:data>
  <error:stack>
    <error:frame>
      <error:xquery-version>1.0-ml</error:xquery-version>
    </error:frame>
  </error:stack>
</error:error>
```

**Comment by grtjn** [comment]
path.encode("UTF-8") seems to do the trick..

**Comment by hunterwilliams** [comment]
I just came across the same problem with my US English Windows 10 when attempting to load files with Japanese Kanji in the filename. 

Solution:

1. Type **Region** in the start menu. If that doesn't work navigate to **Control Panel\All Control Panel Items\Language\Advanced settings** and then press **"Apply language settings for to the welcome screen ...."**
2. Under **Language for non-Unicode programs** press **Change system locale...**
3. Select the language of the filenames causing the ingestion issue. Note this will cause require a restart.
4. Attempt to reload content. If you get a 400 error about a blank file then you may have picked the wrong language. If the load fails for another reason try starting command prompt by running **cmd /u**

**Comment by dmcassel** [comment]
@hunterwilliams, thanks for providing the info

**Comment by grtjn** [comment]
Hunter suggests it might be worthwhile to add these notes in the Wiki somewhere. Maybe create a page dedicated to Windows issues?

**Comment by grtjn** [comment]
Fixed in dev. Leaving open for the wiki edits..

**Comment by grtjn** [comment]
Wiki section added: https://github.com/marklogic/roxy/wiki/Troubleshooting#windows-issues

Closing issue
