### ISSUE TITLE
multiple bootstraps cause error with URI privilege and no way  to define role in URI privilege

### ISSUE THREAD

**Issue by joecrean** [marklogic/roxy#261]
1. I am trying to create a URI privilege – I used the template in the ml-config.xml however it is missing role information. I derived the names of the missing elements from looking at a serialized existing URI Privilege as in the example below however the roles do not show up in the definition (after a bootstrap).
1. If you run bootstrap more than once with a URI privilege definition then it will complain on the second and subsequent attempts that the URI privilege already exists.(ERROR: [{"qid":null, "type":"string", "result":"Configured privilege conflicts with existing one: name=cedent-269-role-uri; action=\/data\/hrlh\/cedent-269; kind=uri (PRIV-MISMATCH):\nSee MarkLogic Server error log for more details."}]) . Is there something different about setting up a URI privilege? Ideally I would lie to set up lots of roles and URI privileges over time. I definitely want to stick with roxy deployer and not have to script this bit separately… any insights for me on how/why roxy does this?

```xml
   <privilege>
          <privilege-name>@ml.cedent1-role-uri</privilege-name>
          <action>/data/hrlh/@ml.cedent1-user</action>
          <kind>uri</kind>
          <role-ids>
             <role-id>@ml.cedent1-role</role-id>
              <role-id>@ml.hr-role</role-id>
          </role-ids>
    </privilege>
```

**Comment by grtjn** [comment]
I think the samples in ml-config have been changed in the meantime. I don't see roles in privileges anymore. I don't think there is much to fix or improve either. Agree?

**Comment by grtjn** [comment]
I vote to close this one.

**Comment by grtjn** [comment]
Closing for now. Feel free to reopen if you disagree..
