### ISSUE TITLE
Failing tests in untouched hybrid-project

### ISSUE THREAD

**Issue by hutchkintoot** [marklogic/roxy#265]
Hi

I just created a new hybrid-project using dev-branch and marklogic-version 7 to test out the unit-test functionality.

I get one failing test when i run the auto-generated tests via the browser. 

```
in /roxy/lib/request.xqy on line 162,

in req:get("dt", (), "type=xs:dateTime")

variables:
name = "dt"
default = ()
options = "type=xs:dateTime"
type = "xs:dateTime"
max-count = ()
allow-empty = fn:true()
value = "2014-08-11T12:07:45.192734 02:00"
v = ()
in /roxy/lib/request.xqy on line 91,

in req:get("dt", "type=xs:dateTime")

variables:
name = "dt"
options = "type=xs:dateTime"
in /app/controllers/test-request.xqy on line 68,

in xdmp:function(fn:QName("http://marklogic.com/roxy/controller/test-request", "test1"), "/app/controllers/test-request.xqy")()

in /roxy/router.xqy on line 51,

in router:route()

in /roxy/query-router.xqy on line 20,

in
```

It looks like the problem is due to the fact that the value is not a valid string-representation of an xs:dateTime. It lacks the + sign between the fractions of a second and time-zone indicator. 

Regards,
Johan

**Comment by grtjn** [comment]
It goes wrong when fn:current-dateTime() returns a dateTime containing a timezone. More accurately when it is a + timezone. One of the tests does a http request including the date, but the + is not uri-encoded. A + in a uri gets translated to space, hence the error with the space before the timezone..
