### ISSUE TITLE
Add RESTful API Spec Generator

### ISSUE THREAD

**Issue by garyrusso** [marklogic/roxy#285]
Add Swagger or equivalent spec generator tool so that the RESTful API spec can be auto-generated.

Here's an example. => http://petstore.swagger.wordnik.com/#!/pet

**Comment by wcandillon** [comment]
@grtjn Is the documentation at https://docs.marklogic.com/REST/GET/v1/search available in docbook or similar format? If yes it would be fairly trivial to transform it into swagger.

**Comment by grtjn** [comment]
Forgot to ask around. I'll do so next week..

**Comment by grtjn** [comment]
From what I have discovered myself so far it doesn't look like it is in DocBook.

@dmcassel Would it be interesting to put Swagger(like) docs on DMC itself?

**Comment by dmcassel** [comment]
The [/v1/config/resources](https://docs.marklogic.com/REST/GET/v1/config/resources) endpoint documents what extensions are available and, if provided, what parameters they take. Seems like a Swagger plugin could be built to provide docs in that format. 

@grtjn, I think it might be odd to have the current docs plus a Swagger version of them on the same site. However, the data needed to generate a Swagger version is (I think) all contained in the zipped version of the docs.

**Comment by wcandillon** [comment]
@garyrusso I'm not sure if this helps but I've wrote a query that crape the marklogic website to generate a swagger 2.0 spec: https://github.com/28msec/marklogic-connector/blob/wcandillon/queries/private/generate_swagger.jq

Here's an output example: https://dl.dropboxusercontent.com/u/1487285/marklogic-spec.json

**Comment by kefo** [comment]
@wcandillon @garyrusso You can download all the MarkLogic documentation here:  https://docs.marklogic.com/MarkLogic_8_pubs.zip  (available from here https://docs.marklogic.com/)

Once you unzip it, take a look at this file:

/pubs/raw/apidoc/RESTclient.xml

It's not docbook, but it's XML and has to be easier than scrapping the HTML.

**Comment by wcandillon** [comment]
@kefo thks a lot!

**Comment by garyrusso** [comment]
@wcandillon Did you move the swagger generator code?

[https://github.com/28msec/marklogic-connector](https://github.com/28msec/marklogic-connector)

I was hoping to do something with it.

**Comment by grtjn** [comment]
I think this is a nice to have, but more like a potential plugin of some kind, rather than something baked into Roxy (Deployer) itself. I could see someone put an MLPM package together or such, which either directly returns swagger docs based on installed rest options/extensions, or provides a lib that makes it trivial to get that.

Encouraging people to take a stab at this, but closing this Roxy ticket.

**Comment by grtjn** [comment]
@garyrusso https://github.com/28msec/marklogic-connector/issues/7 still shows the content of the deleted generate_swagger.jq in case you are still looking for it..
