### ISSUE TITLE
capture of modules-db does not work anymore

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#298]
I tried to capture the content of a modules-db but that one failed.
./ml test capture --modules-db=sarepta-modules
Retrieving source and REST config from sarepta-modules...
ERROR: No such file or directory @ rb_sysopen - /var/folders/hj/45wrdfss2ll8jhqyy0c2r32c24hql1/T/d20141103-65428-1kxoe0j/src/app/config/config.xqy
ERROR: ["/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:1024:in `initialize'", "/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:1024:in `open'", "/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:1024:in `block in save_files_to_fs'", "/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:1017:in `each'", "/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:1017:in `save_files_to_fs'", "/Users/pkester/Development/StandardNorway/capture/deploy/lib/server_config.rb:946:in `capture'", "deploy/lib/ml.rb:140:in `<main>'"]

The mentioned folder exists but is completely empty.
Talked to Geert about this and apparently the folders are not created before writing the file.
This is probably caused by this function in server_config.rb:
  def save_files_to_fs(target_db, target_dir)
    # Get the list of URIs. We get them in order because Ruby's Dir.mkdir
    # command doesn't have a -p option (create parent).

I changed this (line 1024):
          File.open("#{target_dir}#{uri}", 'wb') { |file| file.write(r.body) }
into this (thanks to Geert!)
          path = "#{target_dir}#{uri}"
          parentdir = File.dirname "#{target_dir}#{uri}"
          FileUtils.mkdir_p(parentdir) unless File.exists?(parentdir)
          File.open("#{path}", 'wb') { |file| file.write(r.body) }
and then it worked again.
Same should apply to line 1006

**Comment by grtjn** [comment]
Fixed in dev
