### ISSUE TITLE
setup.xqy evals with hardwired security database name

### ISSUE THREAD

**Issue by sparnell** [marklogic/roxy#309]
Several evals in this module contain:
<database>{xdmp:database("Security")}</database>
which fails if the 'Security' isn't the right database (or doesn't exist)

**Comment by grtjn** [comment]
There are no references to "Security" any more in setup.xqy, except for `$default-security`. I'm still trying to find a good reason to want to change the Security db. Engineering is highly recommending AGAINST doing so.

Considering closing this ticket..
