### ISSUE TITLE
restart command not working when variable are provide from command line

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#317]
For example:
```ml local restart --ml.password=XXXXXX```

**Comment by grtjn** [comment]
It seems that above changes have a negative side-effect on restart without arguments:

```
$ ./ml local restart
ERROR: undefined method `index' for nil:NilClass
ERROR: ["/Users/gjosten/Projects/github-grtjn/roxy/deploy/lib/server_config.rb:404:in `restart'", "deploy/lib/ml.rb:148:in `<main>'"]
```

line 404 needs an extra check if group exists (if **group &&** group.index...).

**Comment by dmcassel** [comment]
fixed in dev
