### ISSUE TITLE
Integrating Quandl API for Market Data (Reference Data)

### ISSUE THREAD

**Issue by ameydhavle** [marklogic/roxy#327]
Recently came across https://github.com/knrz/Quandl-Ruby and was hoping if we can integrate this with roxy.
Quandl is a api that provides Market-Data (mainly Finserv and other economic indicators)

Examples of Quandl Ruby wrapper: 
#### Example from: http://www.quandl.com/help/api#A-Simple-Example

gdp = Quandl::Dataset.get('FRED/GDP') 
#### Example from: http://www.quandl.com/help/api#Getting-Metadata

oil_metadata = Quandl::Metadata.get('NSE/OIL')
#### Example from: http://www.quandl.com/help/api#A-Multiset-Example

datasets = ['FRED/GDP/1', 'DOE/RWTC/1', 'WIKI/AAPL/4']
comparison = Quandl::Multiset.get(datasets).
               collapse(:annual).
               transform(:rdiff).
               limit(10)

**Comment by grtjn** [comment]
Looking back, I think Paxton is right, this should be separate. I'd see most value in an MLPM package, but since Amey is talking about Ruby code, a separate wiki or gist with app_specific code would work best I think.

Closing this ticket.
