### ISSUE TITLE
Add group/server/database settings to help

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#328]
It would be nice if all supported settings could be listed somewhere, possibly with supported min-versions. Maybe something that can be generated out of the settings variables within setup.xqy. Maybe with a command like:

```
ml settings [ group | task-server | http-server | odbc-server | xdbc-server | database ]
```

Could also take server-version into account, with optional override from command-line?

**Comment by dmcassel** [comment]
cool, I like this. fixed in dev
