### ISSUE TITLE
MLCP path with spaces fails

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#334]
Spaces in paths are less common in Unix-like environment, but frequent in Windows. Using an mlcp-home path containing spaces causes the Java call to MLCP to fail. Server_config.rb needs to be changed. Replace:

`runme = %Q{java -cp #{classpath}`

With:

`runme = %Q{java -cp "#{classpath}"`

**Comment by dmcassel** [comment]
fixed in dev
