### ISSUE TITLE
ML8 doesn't support REST property error-format

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#336]
Using a new Roxy REST project against MarkLogic 8 will give this error at deploy rest:

```
ERROR: 400 "Bad Request"
ERROR: {"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"RESTAPI-UNSUPPORTEDPROP", "message":"RESTAPI-UNSUPPORTEDPROP: (err:FOER0000) Unsupported property:  : error-format"}}

```
Workaround: get rid of that line in rest-api/config/properties.xml. We should get rid of that line in the sample version of that file..

**Comment by dmcassel** [comment]
updated in dev
