### ISSUE TITLE
ml-config.sample.xml causes roxy to not bootstrap app servers in dev branch

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#348]
The xml structure in ml-config.sample.xml, when used to init a new Roxy project, results in xml that doesn't properly transform to the desired <configuration>. The app servers are not included under the group xml and thus are not bootstrapped.

**Comment by grtjn** [comment]
I'll look into it tomorrow..

**Comment by grtjn** [comment]
Can you send me the resulting config offline?

**Comment by grtjn** [comment]
Never mind, I found the issue, I already knew about this one, but somehow forgot to file a bug and fix it. The sample config is missing an ns decl for groups..

**Comment by grtjn** [comment]
Fixed in dev
