### ISSUE TITLE
Capture configs is unable to capture users and roles when specified by name

### ISSUE THREAD

**Issue by alencruz** [marklogic/roxy#353]
The setup:get-configuration function in setup.xqy used only ids to return users and roles. This prevented the capture configurations option from capturing users and roles specified by name in the current project configuration or as a parameter. This was a documented “TODO” in the code in order to improve the capture functionality. 
I have added this capability and will be submitting a pull request momentarily. The setup:get-configuration function will now take user/role names or ids as a parameter and return the requested configurations.

**Comment by grtjn** [comment]
Fixed in dev
