### ISSUE TITLE
Make it easy to run MLCP with non-admin user

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#359]
If I want to load data via mlcp as a non-admin user I can't unless I hand jam server_config.rb or run mlcp directly. I threw a quick fix into my current project, but this should be slightly more extensible.

server_config.rb line 847ish....

```ruby
username = @properties['ml.default-user']
password = @properties['ml.appuser-password']
if ARGV.length > 0
  password_prompt
  connection_string = %Q{ -username #{username} -password #{password} -host #{@properties['ml.server']} -port #{@properties['ml.xcc-port']}}
```

Ideally I'd have a mlcp.user= and mlcp.password= so I can overwrite them with anything.

default them to:
```
mlcp.user=${user}
mlcp.password=${password}
```
then let users do whatever in their properties files.

**Comment by grtjn** [comment]
I'd go for mlcp.user. I don't think default-user will be a good default choice.

Note: you can add permissions and collections using mlcp options..
