### ISSUE TITLE
Need better error message when appserver not found in execute_query

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#360]
execute_query can take an appserver as a parameter. properties[:app_name]

if the name provided is not a valid appserver name Roxy will fall back on any old database. Instead, it should throw an error telling the user that the appserver name they provided is not valid. Having just debugged this for 20 minutes I think it will save folks time.

**Comment by grtjn** [comment]
+1 :-)


Sent from Samsung Mobile

**Comment by grtjn** [comment]
I added clearer messages as part of the fix for #661 (see PR #768). Fixed in MASTER
