### ISSUE TITLE
Support a new type of application for those which are neither REST nor MVC

### ISSUE THREAD

**Issue by evlist** [marklogic/roxy#362]
MarkLogic is way too versatile to see its applications fall follow one of these two design patterns and while it is [possible to package and deploy generic applications with Roxy](http://stackoverflow.com/questions/28278234/can-roxy-be-used-to-deploy-generic-marklogic-applications/28279288) this would be more straightforward with a new type of application (which could be called "raw", "generic", ...) which would behave like MVC but generate an empty `src` sub-directory.

**Comment by dmcassel** [comment]
Requirements:

- empty src directory, as done for app-type=rest
- no rewriter, no error handler (to be provided by developer later)

**Comment by grtjn** [comment]
Open for voting:

`--app-type=bare`

**Comment by evlist** [comment]
+1 for `--app-type=bare`.

**Comment by evlist** [comment]
Sorry for the noise, but why is the "close" button so close to "comment"?

**Comment by hutchkintoot** [comment]
+1 for ```--app-type=bare```

**Comment by grtjn** [comment]
Fixed in dev
