### ISSUE TITLE
deploy modules throws 404 error after upgrade to ML8

### ISSUE THREAD

**Issue by nizdobs** [marklogic/roxy#370]
I upgraded my ML server to ML8 today. Now when I deploy modules on roxy I get a 404 error even though the modules appear to have loaded properly.

Any thoughts on why I'd get the 404?

Thanks.
I issued the command: `bash ml local deploy modules -v`

The console showed: 
```loading: /cygdrive/c/Users/nizdobs/Dropbox/MarkLogic/roxy/roxy/restApp/src/ajax/test.html => /ajax/test.html
using dbid: 1046177332298282927```
```Closing HTTP connection to localhost:8002```

```Loaded 15 documents from /cygdrive/c/Users/nizdobs/Dropbox/MarkLogic/roxy/roxy/restApp/src to localhost:8074/restApp-modules at 02/08/2015 06:57:07 pm```

```url: http://localhost:8073/v1/config/properties```
```ERROR: 404 "Not Found"```
```ERROR:```

* Note: I skipped most of the verbose messages showing the files that loaded. *

**Comment by dmcassel** [comment]
"deploy modules" has multiple steps. Sounds like src got deployed to the modules database, but the properties (rest-api/config/properties.xml) failed. Try updating the server-version property to 8. 

There were changes to the REST API's rewriter; I'm also wondering if that's involved.

**Comment by nizdobs** [comment]
I had one project where I defined that --server-version=8 when it was created. It too throws this error when deploying modules

**Comment by paxtonhare** [comment]
See if this one fixes you up: https://github.com/marklogic/roxy/issues/336

**Comment by joemfb** [comment]
I'm having the same problem, and it's not #336. I'll update here once I narrow it down.

**Comment by joemfb** [comment]
fixed in dev
