### ISSUE TITLE
Deploy modules not honoring modules root

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#371]
server_config.rb line 1155ish:

```ruby
total_count = load_data xquery_dir,
                              :add_prefix => "/",
                              :remove_prefix => xquery_dir,
```
should be:

```ruby
total_count = load_data xquery_dir,
                              :add_prefix => @properties["ml.modules-root"],
                              :remove_prefix => xquery_dir,
```

**Comment by grtjn** [comment]
Sure that is a bug? I'd expect src/ paths to load as is..


Sent from Samsung Mobile

**Comment by paxtonhare** [comment]
Let's say I have my modules root set in my http server to /app/version2/.

That means that my http server treats /app/version2/ as / when service up xquery files.

Now if my src/ dir on my drive looks like:

src/some.xqy

and it gets loaded on the server to /some.xqy then it will be invisible to my appserver.

But if we make the change I proposed above, the file will be loaded to /app/version2/some.xqy and will appear to the http server as /some.xqy.

@grtjn do you still think it's not a bug?

**Comment by grtjn** [comment]
I think it depends on what you would expect the deployer to do. :)

How I used it:

- src/app1/some.xqy
- src/app2/some2.xqy
- app1 with root /app1/
- app2 with root /app2/

So, if you have an app with /app/version2/ as root, I'd expect some.xqy on the path src/app/version2/some.xqy

I do see where you want to go, but that is new functionality I think. I would propose introducing a new property for that, something like modules-root-prefix=/app/version2

**Comment by grtjn** [comment]
Or better: `modules-prefix=/app/version2`

**Comment by paxtonhare** [comment]
Ok, Geert. I agree that it is an enhancement rather than a bug. And I like modules-prefix.

I'll add a modules-prefix=/ to the default.properties and then in server_config.rb I'll do:

```ruby
total_count = load_data xquery_dir,
                              :add_prefix => @properties["ml.modules-prefix"],
                              :remove_prefix => xquery_dir,
```

Sound good to you?

**Comment by grtjn** [comment]
Sounds excellent! :)

**Comment by grtjn** [comment]
@paxtonhare were you working on a PR for this?

**Comment by paxtonhare** [comment]
I had planned to work on it but got distracted. No current plans to do this right now.
