### ISSUE TITLE
RFE: show app_specific.rb methods in help output

### ISSUE THREAD

**Issue by joemfb** [marklogic/roxy#374]
I'm often opening up or `cat`'ing `deploy/app_specific.rb` to see what custom methods are available. It'd be handy to have them available in the `./ml -h` command output.

**Comment by grtjn** [comment]
+1

I have been thinking about that recently as well. Not sure you can list them using introspection, but you can append to the Help class..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Joseph Bryan <notifications@github.com> 
Datum: 13-02-2015  23:57  (GMT+01:00) 
Aan: marklogic/roxy <roxy@noreply.github.com> 
Onderwerp: [roxy] RFE: show app_specific.rb methods in help output (#374) 
 
I'm often opening up or cat'ing deploy/app_specific.rb to see what custom methods are available. It'd be handy to have them available in the ./ml -h command output.

**Comment by grtjn** [comment]
Experimented a bit. How about:

Help.rb changes:

```ruby
  def self.usage
    help = <<-DOC.strip_heredoc

      Usage:
        ml [ENVIRONMENT] COMMAND [ARGS]

      General commands (no environment):
         ...
    DOC
    
    help += app_specific || ''

    help += <<-DOC.strip_heredoc

      All commands can be run with -h or --help for more information.
    DOC
    
    help
  end
  
  def self.app_specific
    #stub
  end
```

And then you append this to app_specific.rb:

```ruby
class Help
  def self.app_specific
    <<-DOC.strip_heredoc

      App-specific commands:
        example       Installs app-specific alerting
    DOC
  end
end
```

**Comment by grtjn** [comment]
Fixed in dev

**Comment by joemfb** [comment]
Awesome, thanks Geert!
