### ISSUE TITLE
Make sure field-value-searches works at field level

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#405]
field-value-searches should work at the database level and the field level, but we have a report of it not working at the field level when added to ml-config.xml. This ought to work:

    <field>
      <field-name>verladerNummer</field-name> 
      <field-path> 
        <path>PcsRef[CRlTyCd eq "VL"]/PcsRef</path> 
        <weight>1</weight>
      </field-path>
      <word-lexicons/>
      <tokenizer-overrides/>
      <field-value-searches>true</field-value-searches>
      <trailing-wildcard-searches>true</trailing-wildcard-searches>
      <included-elements/>
      <excluded-elements/>
    </field>

**Comment by grtjn** [comment]
It actually looks like it is supported, but with a different name. It probably works if you use `value-searches` instead of `field-value-searches`.

I recommend allowing both though, as `field-value-searches` is the way ML saves the setting inside databases.xml. Working on a PR for this..

**Comment by grtjn** [comment]
Thnx to @steliann for reporting the issue..

**Comment by grtjn** [comment]
PR pending..
