### ISSUE TITLE
Add ability to deploy JavaScript REST Extensions

### ISSUE THREAD

**Issue by garyrusso** [marklogic/roxy#413]
ML8 Server Side JavaScript has an ability to deploy JavaScript REST Extensions.

This ability is posted here. http://docs.marklogic.com/guide/rest-dev/extensions#id_27816

It would be nice to have an ability to deploy server side java script code (sjs files) in the same way that  XQuery REST extension code is done today.

**Comment by grtjn** [comment]
I think this is already implemented in the dev branch, see also #377, and PR #385. You can select the dev branch at new with `./ml new myname --branch=dev` or upgrade to it using `./ml upgrade --branch=dev`

**Comment by grtjn** [comment]
@garyrusso does the dev branch work for you?

**Comment by grtjn** [comment]
I think we can close this. Agree?

**Comment by paxtonhare** [comment]
Close it.
