### ISSUE TITLE
Allow deploy rest-config

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#415]
You can now be more specific with regard to deploying modules (src, rest, transforms, etc), but you cannot yet deploy only rest config and options. I suggest adding:

```
./ml local deploy rest-config
```

**Comment by dmcassel** [comment]
Rest extensions and transforms are a bit slow to deploy, so I can see this being appealing for someone testing out options.

**Comment by bsdang** [comment]
+1

**Comment by dmcassel** [comment]
Seems like this should be pretty simple -- just pulling a few lines into its own function and make that accessible directly.

**Comment by grtjn** [comment]
Fixed in dev
