### ISSUE TITLE
Some sort of ignore file for ./ml local deploy modules

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic/roxy#419]
I ran into some utf-8 errors when I try to deploy GRUNT NPM modules into MarkLogic using `./ml local deploy modules`...  I am wondering if there is a way to set up some sort of config file that will allow the `./ml local deploy modules` to ignore some troubled files that are in a NPM package...

**Comment by grtjn** [comment]
There is a kind of undocumented feature that allows you to add an `ignore-folders` property, which takes a regex pattern (don't include ^ and $, they are appended automatically). Would that already help?

@paxtonhare It has been asked before, can you specify different encodings somehow?

**Comment by paxtonhare** [comment]
Not sure how you would specify different encodings

**Comment by rlouapre** [comment]
I am not usre if it is an encoding issue. I run into similar issue where ```ml deploy modules``` failed when trying to deploy unnecessary npm modules.

I fix it using ```ignore-folders``` suggested by @grtjn :  
```
ignore-folders=.*/src/(test/mocha|main/node_modules/xquerrail2.framework/node_modules)/.*
```

**Comment by grtjn** [comment]
@paxtonhare MarkLogic is expecting UTF8, but maybe some of those node_modules files are non-UTF8. I assume the ruby xcc library is reading files with ruby, and then streaming the contents with http. Can you read them with a specific encoding, and then convert the stream to utf8 explicitly for instance? Not sure how to configure that, but I'd think that would be kind of the approach..

**Comment by grtjn** [comment]
The encoding part of this ticket is covered by #181, the ignore part is already supported. Closing this ticket.
