### ISSUE TITLE
Question: roxy variables in mlcp 

### ISSUE THREAD

**Issue by nizdobs** [marklogic/roxy#426]
When I type `ml mlcp --help` I learned that:
`Roxy applies variable substitution within option files. You may use variables like:`
`-input_file_path`
`${ml.data.dir}/`

So I prepared an options file, User1mlcpOptions.txt, with the following text:
`-host localhost -username admin -password admin -port 8041 -input_file_path ${ml.data.dir}/User1Files`

and I invoked mlcp through roxy by from a terminal by typing:
`bash ml local mlcp import -options_file User1mlcpOptions.txt` 

And it returned the following message:
`15/05/01 12:58:34 ERROR contentpump.ContentPump: Error parsing command arguments: `
`15/05/01 12:58:34 ERROR contentpump.ContentPump: Unrecognized option: -host localhost -`username admin -password admin -port 8041 -input_file_path ${ml.data.dir}/User1Files`

The data files to load are located in: `/home/sandy/Dropbox/MarkLogic/Tech/SecurityDemo/SecurityDemo-roxy/data/User1Files`

When I type `ml local info` I am told that `ml.data.dir:` `/home/sandy/Dropbox/MarkLogic/Tech/SecurityDemo/SecurityDemo-roxy/data`

So it looks like things are pointed to appropriate directories.

What am I doing wrong here?

Thanks,

- Sandy

**Comment by paxtonhare** [comment]
Sandy,

 It looks like the help text is incorrect. You should be writing them like
so:

-input_file_path
@ml.data.dir/

**Comment by grtjn** [comment]
The error comes from MLCP. You need to put arg names and values each on a separate line..

-input_file_path
somedir
...

**Comment by dmcassel** [comment]
fixed in dev
