### ISSUE TITLE
Help folks stuck on ruby 1.8.7

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#427]
A lot of Roxy users are stuck on ruby 1.8.7 for whatever reason. Try to make their lives a bit easier.

Here's the first one:
ERROR: undefined method `body=' for #<Net::HTTPOK 200 OK readbody=true>
ERROR: ./deploy/lib/server_config.rb:425:in `bootstrap'deploy/lib/ml.rb:144:in `send'deploy/lib/ml.rb:144

I have a patch. Just need to do a pull request.

**Comment by grtjn** [comment]
+10! There might be other tickets talking about things like this..

**Comment by paxtonhare** [comment]
I'm closing this until other issues appear
