### ISSUE TITLE
triggers-db = modules-db with version 1.7.2

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#431]
In Roxy 1.7.2 I am not sure how to setup ml-config.xml and properties to use triggers-db = modules-db

See my comment https://github.com/grtjn/roxy/commit/902810059f24166fdca82c9bc97bdf9c540fb9b1

This suggestion https://github.com/marklogic/roxy/issues/361#issuecomment-72929826 does not seem to work.

**Comment by paxtonhare** [comment]
I left a comment in the other place but this is a legit find. Thanks @rlouapre .

**Comment by grtjn** [comment]
I'll take a close look asap..

**Comment by grtjn** [comment]
Fixed in dev
