### ISSUE TITLE
map:get($req-map, "req-body") is returning NULL via POST in the body

### ISSUE THREAD

**Issue by jeet1212** [marklogic/roxy#434]
Hi,

After upgrading ML6 to ML8, the  map:get($req-map, "req-body") is returning NULL. If I use xdmp:get-request-body(), this starts working. data is being sent in the body via POST in JSON format to create/save XML files in the DB. 

Though I have not upgraded the roxy with latest version. I wanted to take latest version of roxy however the roxy is very much customized based on the customer requirement. If I have to upgrade it, might be I need to go through one by one file.

Multiple roxy modules has been overridden.

Please suggest whether 

Regards,
Indy

**Comment by jeet1212** [comment]
I got the issue. Again this is due to JSON, The json content is in body and it is not setting the value of request body as it is not either type of element() or text() so going into the else () condition.

This is in the router.xqy. This router.xqy is not under /roxy/. This is under /app/lib/router.xqy and customized. 
 
if (fn:exists(xdmp:get-request-body())) then
	      (
	          
	          map:put($req:request, "req-body",
                      if (xdmp:get-request-body()/node() instance of element()) then
                        xdmp:get-request-body()/node()
                      else if (xdmp:get-request-body()/node() instance of text()) then
                        xdmp:quote(xdmp:get-request-body()/node())                     
                      else ( )
                  ) 
           ) 

If I add one more condition like below in above code, everything starts working fine. even I don't need to change any other functions to handle json in the API layer (same I posted in developer community).  
 else if (xdmp:get-request-body()/node()) then
   xdmp:quote(xdmp:get-request-body()/node())

Is there any best check that I can add in place of above line of code?

router.xqy
-------------

declare function router:route()
{
  (: add HTTP header information to the request parameter object :)
	let $x := (
	      map:put($req:request, "req-header",
              element header {
                for $header in xdmp:get-request-header-names()
                 return
                  element {fn:lower-case($header)} {
                    xdmp:get-request-header($header)
                  }
              }
	      ),
	      if (fn:exists(xdmp:get-request-body())) then
	      (
	          
	          map:put($req:request, "req-body",
                      if (xdmp:get-request-body()/node() instance of element()) then
                        xdmp:get-request-body()/node()
                      else if (xdmp:get-request-body()/node() instance of text()) then
                        xdmp:quote(xdmp:get-request-body()/node())
                      else if (xdmp:get-request-body()/node()) then
                      (
                        xdmp:quote(xdmp:get-request-body()/node())
                        ,
                        xdmp:log("else Indy")
                      ) 
                      else (
                       xdmp:log("Indy deo")
                      )
                  ) 
           )       
	      else (),
	      router:set-format()
	 )

	(: PRawal : Checks authentication before executing the request :) 	
	let $valid-request := 
	      if(fn:not($config:SESSION-AUTHENTICATE)) then fn:true() 
          else if(xs:string($controller) = ("ping")) then fn:true()
          else if(xs:string($controller) = ("login")) then fn:true()
          else if(xs:string($controller) = ("logout")) then fn:true()
          else if(xs:string($controller) = ("verify")) then fn:true()
          else if(xs:string($controller) = ("setcache")) then fn:true()
          else if(xs:string($controller) = ("browseCalibration")) then fn:true()
          else if(xs:string($controller) = ("sessions")) then fn:true()
          else if(xs:string($controller) = ("forgetpassword")) then fn:true()
          else if(xs:string($controller) = ("resetpassword")) then fn:true()
          else auth:authenticate()

  (: run the controller. errors bubble up to the error module :)
	 let $data := 
	   if($valid-request) then 
	   (
            if(fn:string($valid-request)="true") then
                xdmp:apply(xdmp:function(
                    fn:QName(fn:concat("http://marklogic.com/roxy/controller/", $controller), $func),
                    $controller-path)) 
             else if(fn:string($valid-request) = "timeout") then (
                   xdmp:apply(xdmp:function(
                        fn:QName(fn:concat("http://marklogic.com/roxy/controller/login"), "login-timeout"),
                        $login-controller-path))                
             ) else (
                   xdmp:apply(xdmp:function(
                        fn:QName(fn:concat("http://marklogic.com/roxy/controller/login"), "login-error"),
                        $login-controller-path))
             
             )
        )	                            	 
        else 
        (        	 
    	   xdmp:apply(xdmp:function(
                fn:QName(fn:concat("http://marklogic.com/roxy/controller/login"), "login-error"),
                $login-controller-path))
        )


	(: Roxy options :)
	let $options :=
	  for $key in map:keys($ch:map)
	  where fn:starts-with($key, "ch:config-")
	  return
	    map:get($ch:map, $key)

	(: remove options from the data :)
	let $_ :=
	    for $key in map:keys($ch:map)
	    where fn:starts-with($key, "ch:config-")
	    return
	       map:delete($ch:map, $key)

	let $format as xs:string := ($options[self::ch:config-format][ch:formats/ch:format = $format]/ch:format, $format)[1]
	let $_ := (
	      for $header in map:get($ch:map, "res-header")/* 
	      return 
	           xdmp:add-response-header(fn:local-name($header), $header/fn:string()),
	           xdmp:set-response-code((map:get($ch:map, "res-code"), 200)[1],(map:get($ch:map, "res-message"), "OK")[1]) 
	      )

	(: controller override of the view :)
	let $view := ($options[self::ch:config-view][ch:formats/ch:format = $format]/ch:view, $default-view)[1][. ne ""]


	(: controller override of the layout :)
	let $layout :=
	  if (fn:exists($options[self::ch:config-layout][ch:formats/ch:format = $format])) then
	    $options[self::ch:config-layout][ch:formats/ch:format = $format]/ch:layout[. ne ""]
	  else
	    $default-layout


	(: if the view return something other than the map or () then bypass the view and layout :)
	let $bypass as xs:boolean := fn:exists($data) and fn:not($data instance of map:map)

	return
	  if (fn:not($bypass) and (fn:exists($view) or fn:exists($layout))) then
	    let $view-result :=
	      if (fn:exists($ch:map) and fn:exists($view)) then
	        rh:render-view($view, $format, $ch:map)
	      else
	        ()
	    return
	      if (fn:not($bypass) and fn:exists($layout)) then
	        let $_ :=
	          if (fn:exists($view-result) and
	              fn:not($view-result instance of map:map) and
	          	  fn:not(fn:deep-equal(document {$ch:map}, document {$view-result}))) then
	            map:put($ch:map, "view", $view-result)
	          else
	            map:put( $ch:map, "view",
	              for $key in map:keys($ch:map)
	              return
	                map:get($ch:map, $key) )
	        return
	          rh:render-layout($layout, $format, $ch:map)
	      else
	        $view-result
	  else if (fn:not($bypass)) then
	    for $key in map:keys($ch:map)
	    return
	      map:get($ch:map, $key)
	  else
	    $data,
	    xdmp:log( fn:concat("TEST#1 - ", xdmp:get-original-url()," - Time - ",xdmp:elapsed-time()),"info")
};

**Comment by jeet1212** [comment]
I modified the condition like below. Hope this time, I should be correct :)

  else if (xdmp:get-request-body()/node() instance of object-node()) then
    xdmp:to-json(xdmp:get-request-body()/node())/node()
  else ()

Complete condition-
-----------------------------
if (fn:exists(xdmp:get-request-body())) then
	      (	          
	          map:put($req:request, "req-body",
                      if (xdmp:get-request-body()/node() instance of element()) then
                        xdmp:get-request-body()/node()
                      else if (xdmp:get-request-body()/node() instance of text()) then
                        xdmp:quote(xdmp:get-request-body()/node())
                      else if (xdmp:get-request-body()/node() instance of object-node()) then
                         xdmp:to-json(xdmp:get-request-body()/node())/node()
                      else ()
                  ) 
           )       
	      else ()

**Comment by dmcassel** [comment]
I was just running some tests. I think what you have there will work. If "instance of object-node()" doesn't work, you should be able to fall back on node(), as long as you've done the element() test before it. 

Looks like you've got this. Make sense to close the ticket?

**Comment by jeet1212** [comment]
Thank you David for your help and time so should I add one more condition like below for the safer side. in case, not any type check is applicable,

 if (fn:exists(xdmp:get-request-body())) then
	      (
	          
	          map:put($req:request, "req-body",
                      if (xdmp:get-request-body()/node() instance of element()) then
                        xdmp:get-request-body()/node()
                      else if (xdmp:get-request-body()/node() instance of text()) then
                        xdmp:quote(xdmp:get-request-body()/node())
                      else if (xdmp:get-request-body()/node() instance of object-node()) then
                         xdmp:to-json(xdmp:get-request-body()/node())/node()
                      else if (xdmp:get-request-body()/node()) then
                         xdmp:quote(xdmp:get-request-body()/node())   
                      else ()
                  ) 
           )   

Yes, we can close the ticket now. Thank you again!
