### ISSUE TITLE
Question: import existing certificate into certificate template

### ISSUE THREAD

**Issue by matthewdooler** [marklogic/roxy#435]
Hi,

We would like to have roxy create a new certificate template, and then import an existing signed certificate from the filesystem into the template.

We've followed these steps to setup the template (https://github.com/marklogic/roxy/wiki/Security#ssl) but wondering if it would be possible to then import an existing certificate automatically without having to go to the admin page.

Thanks!

**Comment by grtjn** [comment]
Have no experience with this, but looks like the pki library is meant for that: http://docs.marklogic.com/pki. If you can automate the import with these from for instance QConsole, then we should be able to adjust ml-config.xml and the deployer to allow for automatically importing this.. I can imagine having a cert/ folder, where you have a file matching the template name or something like that?

**Comment by MatthewDooler** [comment]
I ended up using just that, with a custom build step in app_specific.rb:

    def import_certificate()
      @logger.info("Importing certificate")
      r = execute_query(%Q{
        xquery version "1.0-ml";
        import module namespace pki = "http://marklogic.com/xdmp/pki" at "/MarkLogic/pki.xqy";
        
        pki:insert-host-certificate(
          pki:template-get-id(pki:get-template-by-name("#{@properties["ml.ssl-certificate-template"]}")),
          xdmp:document-get(
            "#{@properties["ml.ssl-host-certificate-filename"]}",
            <options xmlns="xdmp:document-get">
              <format>text</format>
            </options>
          ),
          xdmp:document-get(
            "#{@properties["ml.ssl-host-certificate-key-filename"]}",
            <options xmlns="xdmp:document-get">
              <format>text</format>
            </options>
          )
        )
      },
      :db_name => @properties["ml.content-db"]
    )
    @logger.info(r.body)
    end

It would be great if this could be included in vanilla roxy!

Probably worth mentioning that we didn't actually end up using this, as our certs are issued by an intermediate CA and MarkLogic doesn't send the full CA chain. We had to use Apache SSL termination to get it working.

**Comment by cyanline** [comment]
Matt, are you able to successfully deploy a marklogic rest-app via roxy that uses an ssl-template?
