### ISSUE TITLE
Tie roxy './ml local deploy modules' into grunt watch

### ISSUE THREAD

**Issue by sgehringDesign** [marklogic/roxy#436]
This is more of a question...  Would it be possible to tie roxy `./ml local deploy modules` into a `grunt watch`?   This way when my local grunt watch detects a change to my LESS or JS code it will push the built code to into my local MarkLogic DB?

**Comment by rlouapre** [comment]
watch from ```grunt``` or ```gulp``` should not be an issue.
We are using similar technique to rebuilt ```dist``` directory [1]

Can Roxy only deploy the files changed as opposed to the entire src directory?

[1] - https://github.com/nativelogix/xquerrail2.framework/blob/master/gulpfile.js#L114-L120

**Comment by dmcassel** [comment]
You could tell grunt (or gulp) to call "ml local load...". See "ml load -h" for details; it's for loading a single file. It defaults to the content database, but you can tell it to use the modules database instead.

**Comment by rlouapre** [comment]
@dmcassel thanks for the tip ```ml {env} load```

I have created a gist using gulp / watch https://gist.github.com/rlouapre/f4d1e257dda43364995f

**Comment by dmcassel** [comment]
I like it. @grtjn, something to add to the slush generator?

**Comment by grtjn** [comment]
Ha, would be nice if gulp could leverage roxy properties directly, instead of you needing to duplicate settings inside gulpfile.js. Maybe by reading ./ml local info with some output format? :)

Yes, definitely worth considering to add to the slush template. I'll open a ticket..

**Comment by rlouapre** [comment]
@grtjn that was the point of https://github.com/marklogic/roxy/issues/437

**Comment by grtjn** [comment]
Hereby referenced.. ;-)

**Comment by stephen-gehring-ml** [comment]
THANKS! =O)

**Comment by dmcassel** [comment]
I think that this kind of integration is a combination of #437 and work external to Roxy. With that in mind, I propose closing this ticket. Anybody see something else to be done here?

**Comment by grtjn** [comment]
A ticket was opened in the slush project, +1 for closing..
