### ISSUE TITLE
Export properties for a given environment

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#437]
I am looking for a way to export the list of propertie for a given environment and I was planning to use ```ml info``` for that. 
The idea is to reuse the parameter defined in Roxy for other tools (gulp, mocha...).
The current format used by ```ml info``` can be easily formatted but we need to be careful with providing more feedback https://github.com/marklogic/roxy/issues/414#issuecomment-100589864.
It would be event easier if Roxy could support standard format: ```xml```, ```csv``` or ```yml```.
Or is there a better way than using ```ml info```

@paxtonhare - how MarkLogic Sublime does it?

**Comment by grtjn** [comment]
It should be almost trivial to convert the output of ml info with sed or awk I'd say, but interesting anyhow I think.

XML or JSON output makes sense. CSV makes a bit less sense to me. INI or properties style more. And the current output is already compatible with YML I think, except that it is lacking hierarchy?

**Comment by rlouapre** [comment]
Why would I need additional command line tools to convert it? 
They might be available on OSX or Linux but maybe not out of box on Windows :smiley:

I am not sure the current is compatible with yml:
```
IS_JAR: false
Properties:
ml.xquery.dir: D:/Projects/ml/xxx/src
ml.xquery-test.dir: D:/Projects/xxx/roxy/src/test
ml.xcc-server-name: 8271-xxx-xdbc
...
```

I am happy to implement this feature once we agree on the supported format.

**Comment by grtjn** [comment]
I meant sed and awk as a workaround.

I would be happy with something like `ml local info --format=xml`. @paxtonhare, @dmcassel?

**Comment by dmcassel** [comment]
Seems reasonable to me. Something like: `ml local info --format=json`

    {
      "isJar": false,
      "properties": {
        "ml.xquery.dir": "/Users/dcassel/git/roxy-dmc/src",
        "ml.xquery-test.dir": "/Users/dcassel/git/roxy-dmc/src/test",
        ...
      }
    }

**Comment by dmcassel** [comment]
fixed in dev
