### ISSUE TITLE
Use different credentials for ml {action} modules

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#438]
Is there a way to provide different credentials for ```ml {action} modules```?

I currently need to create Roxy another environment and override ```user``` and ```password``` properties from the command line.

It could even make sense to only use ```admin``` for ```ml bootstrap```

**Comment by grtjn** [comment]
Interesting. How about bootstrap-user/-password, deploy-user/-password, both defaulting to user/password. First to be used for bootstrap/wipe/restart, the other for anything else (deploy/clean/app_specific)?

**Comment by rlouapre** [comment]
:+1:

**Comment by grtjn** [comment]
Nice to have, pushing away for the moment.. (should be easy though..)

**Comment by grtjn** [comment]
Whoops, accidentally closed this..

**Comment by RobertSzkutak** [comment]
PR For this now merged into dev. Separate users now supported for bootstrap, deploy, mlcp and corb.
