### ISSUE TITLE
Capture svn info / git commit on deploy modules

### ISSUE THREAD

**Issue by rlouapre** [marklogic/roxy#441]
I end up writing these 2 extensions for that purpose:
For svn:
```ruby
  alias_method :original_deploy_modules, :deploy_modules
  def deploy_modules()
    modulesRoot = @properties["ml.xquery.dir"]
    svn_info_file = File.new("#{modulesRoot}/svn-info.xml", "w")
    svn_info_file.puts(`svn info --xml`)
    svn_info_file.close
    original_deploy_modules
  end
```
For git:
```ruby
  alias_method :original_deploy_modules, :deploy_modules
  def deploy_modules()
    modulesRoot = @properties["ml.xquery.dir"]
    git_info_file = File.new("#{modulesRoot}/git-info.xml", "w")
    git_info_file.puts(`git log -1 --pretty=format:"<entry><id>%H</id><author>%an</author><date>%ai</date><subject>%s</subject><body>%b</body></entry>"`)
    git_info_file.close
  end
```

**Comment by grtjn** [comment]
Interesting. How do you use that info?

I think we could integrate this, and potentially auto-detect svn or git. Maybe add a toggle to activate it.

ml.add-code-info=true/false

**Comment by rlouapre** [comment]
It is essentially used during development phase when ```deploy modules``` are very frequent and unfortunately manual for some customers.
It help them to be able to tell what revision they are currently using (from qconsole).
It could even be exposed as REST endpoint and output it in ErrorLog.txt

**Comment by dmcassel** [comment]
Looks like you could do something like:

    git rev-parse HEAD

getting the current commit hash, then add that to the repo. That does not indicate whether the repo has any uncommitted modifications, but it's something.

**Comment by dmcassel** [comment]
fixed in dev
