### ISSUE TITLE
Is cert supported as a deployment environment?

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/roxy#442]
In README.mdown 
Section: Configure MarkLogic Server

The file supports local | dev | prod, however the build.sample.properties also has a cert. I do not believe the cert-server works.

**Comment by dmcassel** [comment]
Roxy supports whatever environments you want. You need to do two things: 

- add the environment to the environments property (normally in default.properties; copy it to build.properties)
- define a -server property (if you want cert, add cert-server)

**Comment by dmcassel** [comment]
See also: https://github.com/marklogic/roxy/wiki/Environment-properties#adding-an-environment

**Comment by prestonmcgowan** [comment]
Having the "cert" in the sample is confusing if it isn't configured as a default like the others (local, dev, prod). 
I am suggesting either adding cert to all places needed so it becomes default like the others, or removing cert so it doesn't generate issues.

**Comment by dmcassel** [comment]
Want to do a PR on that one?

**Comment by grtjn** [comment]
I suggest removing it. Adding custom env names is very easy.

**Comment by grtjn** [comment]
Fixed in dev
