### ISSUE TITLE
Missing support for ML 8, but still saying ML 4 is supported

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/roxy#443]
The following files identify MarkLogic 4, 5, 6, 7 but not 8.

server-version in /deploy/default.properties
server-version in /deploy/sample/build.sample.properties

README.mdown
Section: Configure your application

**Comment by dmcassel** [comment]
help.marklogic.com says ML5 is past end-of-life, so I'm dropping that one as well.

**Comment by dmcassel** [comment]
Updated [supported versions wiki](https://github.com/marklogic/roxy/wiki/Supported-MarkLogic-versions).

**Comment by dmcassel** [comment]
fixed in dev
