### ISSUE TITLE
Wipe does not work if you have subdatabases configured

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#455]
I configured a subdatabase in roxy and I could not deploy that to the server. Roxy ignores the subdatabases section in the database config of ml-config.xml
Then I manually configured a subdatabase
When I then try to wipe the application I get this error:
ml local wipe
Wiping MarkLogic setup for your project from ln-test-ml1...
ERROR: ADMIN-DATABASEINUSE: (err:FOER0000) The following databases still refer to this database as their super-databse: ln-generics-schemas.
See MarkLogic Server error log for more details.
ERROR: ... Wipe FAILED
I think before the wipe is executed the subdatabases need to be detached.
I tried this with roxy 1.7.2 on ml8.0-2

**Comment by grtjn** [comment]
I think this was a mistake. To my knowledge super/sub-databases are not yet supported. Would be nice though, there is an interesting use case where you use a sub-database for generic modules!

**Comment by grtjn** [comment]
Implementing #465 will fix this. Closing this issue..
