### ISSUE TITLE
Restart should restart cluster by default

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#456]
If you use multiple groups, and spread hosts across them, you need a restart cluster to get the updates loaded across all hosts. It would be better if `./ml env restart` would restart entire cluster by default, instead of only those hosts attached to group of the bootstrap host..

Not doing a cluster restart will cause subsequent Roxy commands to fail with an `XDMP-SERVERERR`, including restart cluster. You can only get out by manually restarting the hosts/cluster from Admin UI.

**Comment by dmcassel** [comment]
Don't you only need to restart the hosts that are part of a group that has changed? Or are you saying it's hard to figure that out, so it's better to be safe and restart everything?

**Comment by grtjn** [comment]
You could potentially create multiple groups, or move hosts that are not in the same group as the bootstrap host. Restarting cluster is safer..

**Comment by dmcassel** [comment]
Makes sense to me.

**Comment by grtjn** [comment]
Fixed in dev
