### ISSUE TITLE
latest version of mlcp does not see log4j.propeties in mlcp/conf folder

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#459]
I just tested roxy with the latest version of mlcp and I noticed no progress info when executing mlcp.
It does not see the log4j.properties in the conf folder of mlcp.
I added the following to line 1070 of server_config.rb to fix this:
    classpath = jars.join(path_separator).concat(path_separator).concat(ServerConfig.expand_path("#{mlcp_home}/conf"))

**Comment by grtjn** [comment]
Check latest mlcp.sh/.bat for other properties that could/should get added.. (like xcc compat setting)

**Comment by grtjn** [comment]
I added some fixes, but I'm hearing latest MLCP uses win native code that needs to be on the path. Only applies to Windows luckily..

**Comment by grtjn** [comment]
Fixed in dev
