### ISSUE TITLE
For ML 8 consider setting xcc to ${app-port} and install-xcc=false

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/roxy#461]
Since it's now possible to run against the über server without needing to install xcc perhaps we should make that the default for ml 8 installs.

**Comment by paxtonhare** [comment]
hmm. looks like mlcp still can't specify a modules database to use. so that means you can't run transforms if you point to 8000. I guess this request is a bit premature.

**Comment by grtjn** [comment]
Mlcp does support a database option since 1.3, but that is hard to detect. So that doesn't help either..

**Comment by grtjn** [comment]
With regard to modules: you could run against app-port i think..

**Comment by paxtonhare** [comment]
good point on app-port. this worked for me:

app-port=8060
xcc-port=${app-port}
install-xcc=false

So perhaps I need to update the title of this ticket. Make xcc-port the same as app-port

**Comment by grtjn** [comment]
But only for server-version=8, and perhaps show hints/warns if different..

**Comment by joemfb** [comment]
Now a dupe of #373 ;)

**Comment by paxtonhare** [comment]
awesome. and I even commented on the other one. sheesh.
