### ISSUE TITLE
Allow same prop replace syntax in props and ml-config

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#467]
In properties files you use ${app-name}, in ml-config you use @ml.app-name. The difference is confusing to my opinion. And not adding { } in ml-config makes people believe @ml.app-name-rest-modules is a full property name, where it actually is just a partial one (@ml.app-name + '-rest-modules').

I vote for adding different syntax to ml-config as well, preferably ${propname} like in properties themselves, alternatively @{ml.propname}. Thoughts?

**Comment by dmcassel** [comment]
It will have to be backwards-compatible, which means doing two passes. Not sure how many places that happens in the code. Hopefully only once, in which case, no big deal. It would be less confusing.

**Comment by grtjn** [comment]
Any particular reason to have the ml. prefix in ml-config?

**Comment by grtjn** [comment]
Fixed in dev
