### ISSUE TITLE
Group not propagated for servers/databases using @import

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#468]
When you add unit testing to your roxy configuration, the config will be expanded for the test http-server and the test-content database. However, the setup.xqy script does not take the group for the http server and the database into account when it expands the @import attribute. That info effectively gets lost when recreating server and database xml to merge the settings. As a result the server and database end up in the Default group, which may potentially not contain any hosts, so server because unreachable, and the database will have no forests.

This can be fixed by creation of extra function:
```xquery
declare function setup:get-group-name($server-config as element()) as xs:string
{
  (: app servers :)
  if ($server-config/ancestor::gr:group/gr:group-name) then
    $server-config/ancestor::gr:group/gr:group-name
  (: databases :)
  else if ($server-config/@group) then
    $server-config/@group
  (: revert to defaults :)
  else if ($server-config/ancestor::*:configuration/@default-group) then
    $server-config/ancestor::*:configuration/@default-group
  else
    "Default"
};
```

and rewrite the function setup:get-group to :
```xquery
declare function setup:get-group($server-config as element()) as xs:unsignedLong
{
    xdmp:group(setup:get-group-name($server-config))
};
```

In function setup:get-http-appservers-from-config (around line 3463) an attribute group must be added to the gr:http-server element:
```xquery
        element gr:http-server
        {
          attribute group { setup:get-group-name($server) },
          $server/@*[fn:not(fn:local-name(.) = "import")],
          $imported-http/@*[fn:not(fn:local-name(.) = $server/@*/fn:local-name(.))],
```

In function setup:get-databases-from-config (around line 5480) an attribute group must be added to the db:database element:
```xquery
        element db:database
        {
          attribute group {setup:get-group-name($db)},
          $db/@*[fn:not(fn:local-name(.) = "import")],
```

**Comment by dmcassel** [comment]
fixed in dev
