### ISSUE TITLE
Separate out the configuration part for unittesting in server_config.rb

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#469]
In function build_config the configuration file is created as one big config element.
If might be handy to separate out the different parts in separate function so those separate functions can be override in app_specific.
So create a separate function that only handles unit-test specific replacements, and one specific for the triggers db and so on. 
One use-case is when you have a D-node/E-node config where all your data is on the D-nodes and all your http-servers are on the E-nodes and you want to enable the unittest section. You want to override  the assignment and forest-data-directory.
These override statements can be done in an override function in the app_specific.rb file

**Comment by grtjn** [comment]
In a nutshell: you cannot control server, db, and forest creation for generated parts of ml-config, like schemas, triggers, test, rest. You could add properties to allow influencing them from properties files, but overriding function from app_specific might be an elegant approach as well.

We could also support both..

**Comment by dmcassel** [comment]
Fixed in dev
