### ISSUE TITLE
Make http timeout configurable

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#470]
Something like:

HTTP_CONNECTION_READ_TIMEOUT            = ENV['HTTP_CONNECTION_READ_TIMEOUT'] ? ENV['HTTP_CONNECTION_READ_TIMEOUT'].to_i : 300

If you wanted to use the ENV vars. 

If you meant from properties files then it would be something like:

MLClient.rb:
      @http = Roxy::Http.new({
        :logger => logger
        :http_connection_read_timeout => options[:http_connection_read_timeout]
      })

You would just have to pass the timeout around to a few places to get it into the Roxy::Http class.

**Comment by dmcassel** [comment]
Fixed in dev
