### ISSUE TITLE
What privileges are required for bootstrapping and deploying? 

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#491]
I was emailed a question:

> Thank you for the great tool Roxy. We are planning to use Roxy in our project. We would like to understand is it required to use admin user name and password in the environment specific properties file or we can have any other user. If non admin user what are the privileges that the non admin user should have.
> 
> Please let me know whether is it mandatory to use admin credentials or non admin credentials

Seems like a good topic to document in a wiki.

**Comment by dmcassel** [comment]
Short answer: for Roxy, we wanted set up to work with what is available out-of-the-box from MarkLogic, which meant working with the available users. The only default user that has sufficient privileges to run bootstrap is admin. A non-admin user would need a lot of privileges, although in principal it should be possible to set up such a user. 

As an example, a user running bootstrap would need to execute [admin:save-configuration-without-restart](http://docs.marklogic.com/admin:save-configuration-without-restart), which requires the http://marklogic.com/xdmp/privileges/admin-module-write privilege. A user that has all the privileges required for each function in [setup.xqy](https://github.com/marklogic/roxy/blob/master/deploy/lib/xquery/setup.xqy) should be able to bootstrap and deploy.

**Comment by guru2228** [comment]
Thank you.

**Comment by grtjn** [comment]
See also #600, and #624.

**Comment by grtjn** [comment]
Covering this in #600.
