### ISSUE TITLE
setup.xqy fails to validate field range index config (most likely other range-indexes as well)

### ISSUE THREAD

**Issue by joemfb** [marklogic/roxy#492]
Since `setup.xqy` uses the XML snippets from `ml-config.xml` directly, without validating their contents, it's possible to end up with a schema-invalid `databases.xml` configuration. Once that happens the REST Management API throws errors for database updates.

Specifically, I had a database with a `range-field-index` element containing a `namespace-uri` element (from the dmlc-healthcare project). This bootstraps (and works) without issue via Roxy. When I try to configure a database using the REST Management API (using ml-gradle and OBI), the PUT to `/manage/v2/databases/obi-ui-content/properties` fails with a 400 error.

This may properly be a bug of the Admin API not validating it's parameters. I'm not sure what an appropriate resolution would be, but wanted to capture the problem here.

**Comment by grtjn** [comment]
I thought we fixed most of these cases. Which version of Roxy?

**Comment by joemfb** [comment]
This was on v1.7.1, but the implementation is the same on current master: https://github.com/marklogic/roxy/blob/master/deploy/lib/xquery/setup.xqy#L2447

**Comment by grtjn** [comment]
Ah yes, from the looks we forgot to fix path-index, and field-index. Will look asap..

**Comment by grtjn** [comment]
Still applies..

**Comment by grtjn** [comment]
#499/#501 is related, but didn't fix this. Pushing away to allow release of 1.7.3 though..

**Comment by RobertSzkutak** [comment]
Pushing off to the next release...
