### ISSUE TITLE
Problem using ml new without --server-version

### ISSUE THREAD

**Issue by nizdobs** [marklogic/roxy#495]
When I run this command roxy creates a new project without complaint:

`bash ml new junk11 --app-type=rest --branch=dev --server-version=8`

However, if I omit the --server-version flag and run this:
`bash ml new junk11 --app-type=rest --branch=dev`

I get the following error (Note that I had no time to type the server version when prompted. The script ran straight through to the error:
`Creating new Application: junk11...`
`Cloning into 'junk11'...`
`remote: Counting objects: 4044, done.`
`remote: Compressing objects: 100% (15/15), done.`
`remote: Total 4044 (delta 5), reused 0 (delta 0), pack-reused 4029`
`Receiving objects: 100% (4044/4044), 7.76 MiB | 4.80 MiB/s, done.`
`Resolving deltas: 100% (2290/2290), done.`
`Checking connectivity... done.`

`No initial source code is provided for REST apps. You can copy code from Application Builder under the source directory.`
`Required option --server-version=[version] not specified with valid value.`

`  What is the version number of the target MarkLogic server? [5, 6, 7, or 8]`
`ERROR: No such file or directory - junk11`
`ERROR: ["/home/nizdobs/roxy/junk11/deploy/lib/server_config.rb:307:in gets'", "/home/nizdobs/roxy/junk11/deploy/lib/server_config.rb:307:in gets'", "/home/nizdobs/roxy/junk11/deploy/lib/server_config.rb:307:in prompt_server_version'", "/home/nizdobs/roxy/junk11/deploy/lib/server_config.rb:209:in init'", "deploy/lib/ml.rb:126:in <main>'"]`

**Comment by dmcassel** [comment]
What version of ruby are your using?

**Comment by nizdobs** [comment]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by grtjn** [comment]
Could it be that the changes to run 'headless' (for slush-marklogic-node) have caused this side-effect?

**Comment by grtjn** [comment]
Fixed in dev
