### ISSUE TITLE
adding scheduled task to ml-config causes lexval error on bootstrap

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#497]
I have a configuration with multiple hosts, divided over two groups.
I added a scheduled task to the server section in a specific group in ml-config and added a host-name where the task should run. When bootstrapping I get the following error:
ml local bootstrap
Bootstrapping your project into MarkLogic 8 on ln-vm4-ml2...
ERROR: XDMP-LEXVAL: gr:host-id("") -- Invalid lexical value ""
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED

If I change the way the host-name is handled in the function setup:create-scheduled-task
from this:
        $task/gr:task-host/xdmp:host(.),
to this:
        xdmp:host($task/gr:task-host/@name),
and change the way it is configured in ml-config from element content to attribute name, bootstrap will work...

**Comment by grtjn** [comment]
This only happens with schedules assigned to a particular host (with a non-empty task-host element). We should switch to putting host-name in a name attrib, like with databases, users, etc. We should change the code to:

`$task/gr:task-host/@name/xdmp:host(.)`

Do this for all schedule types, check validation, and also have a look at capture..

**Comment by peetkes** [comment]
But when I redo the bootstrap (when it has scheduled tasks) it will fail with this error:
ml local bootstrap
Bootstrapping your project into MarkLogic 8 on ln-vm4-ml2...
ERROR: ADMIN-DEPENDINGSCHEDULEDTASKS: (err:FOER0000) There are depend tasks on the host or the associated group. Delete those first before moving host 15799318952291192588 to a new group.
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED

So probably something has to be changed on the validation sde as well

**Comment by grtjn** [comment]
Related to #500

**Comment by grtjn** [comment]
Fixed in dev..
