### ISSUE TITLE
Speedup Bootstraping of Configuration with Large Number of Indexes

### ISSUE THREAD

**Issue by alencruz** [marklogic/roxy#499]
In the configuration for our project we have a large number of indexes (around 700 indexes). We were experiencing a long time for the bootstrap to complete and were running into timeout errors. The timeout errors were fixed by increasing the Roxy http parameters but the underlying cause was still present. We made some tweaks to the setup.xqy file to perform index configurations (removal and creation) at once, rather than iteratively doing each index. This speed up our bootstrapping for our scenarios by around 90% and we were able to revert back to the default Roxy http parameters. I will be making a pull request with these changes to see if it’s something the project would like to utilize.

**Comment by grtjn** [comment]
Looking forward to the PR!

**Comment by grtjn** [comment]
Fixed in dev
