### ISSUE TITLE
ml errors when run in cygwin

### ISSUE THREAD

**Issue by nizdobs** [marklogic/roxy#504]
Running roxy on cygwin on WIndows 7. When I issued an `ml` command I got the following error:
`ml: line 17: $'\r': command not found`
`ml: line 20: syntax error near unexpected token ```$'\r''``
`'l: line 20: ```usage()`

Some googling told me that this is a problem with unix vs. windows line ending/carriage returns. When I applied `dos2unix ml` the `ml` program ran just fine. However, every time it generates a new `ml` program for a new project the problem came back.

Some other searching suggested that setting a Windows System Environment Variable of `SHELLOPTS=igncr` would address this issue. However, I still get the error when the project specific cloned `ml` gets generated.

I seem to recall that when I installed cygwin I was asked how I want to handle carriage returns but I don't know what setting I chose or how to adjust this. 

Any help is appreciated.

**Comment by kefo** [comment]
Since you are in a windows environment, can you not run the .bat file?  I've seen the same error in an cygwin install and I found that I could just run `ml.bat` instead.

```bash
./ml.bat local deploy modules
```

**Comment by nizdobs** [comment]
I can run the .bat file. I just find this behavior curious because I've run
Roxy from cygwin prompt in the past.

**Comment by kefo** [comment]
Simple question, but curious:  Does this happen when you clone the repository, or otherwise grab the current master or dev branch copy of `ml`?  

I ask because I've been using a copy of Roxy of indeterminate date and I get the carriage return error.  But, I just cloned the current repo and, using cygwin, do not get an error.

(I'm assuming 'yes'; just covering the bases.)

**Comment by rlouapre** [comment]
I had the issue as well and decided (sadly) not to use roxy with cygwin.

```git clone``` will use ```crlf``` git config to convert lf to crlf [1]. There is no .gitattribute in roxy project so it will use git global settings.

Maybe crlf could be applied only in sepcific files [2].

[1] - https://help.github.com/articles/dealing-with-line-endings/
[2] - http://stackoverflow.com/questions/19551037/git-how-to-keep-crlf-endings-for-specific-files-only

**Comment by grtjn** [comment]
Thanks for reporting. I had trouble running Roxy properly in Windows as well. I also tried tools like gitbash, but that seems to fall short as well..

**Comment by grtjn** [comment]
Learned how to fix this for my mlvagrant project, I'll add a .gitattributes for this as soon as I get to it!

**Comment by grtjn** [comment]
Fixed in dev..
