### ISSUE TITLE
POST defaults to query mode

### ISSUE THREAD

**Issue by heelix** [marklogic/roxy#505]
Using MarkLogic 8.0-3.  When attempting to call a function that is in update mode like xdmp:document-insert(..) , the default POST handler will throw a XDMP-UPDATEFUNCTIONFROMQUERY.  Seems somebody decided that non-idempotent requests were better off to default to query mode rather than update.

To set it to update, need to add the rapi:transaction-mode annotation.

declare namespace rapi = "http://marklogic.com/rest-api";
...
declare 
**%rapi:transaction-mode("update")**
%roxy:params("foo=xs:string", "bar=xs:string")
function cs:post(
    $context as map:map,

MarkLogic 8.0-2 seems to share the same brain dead default setting.  I saw different behavior on 8.0-1, not that anyone is using that.

declare option xdmp:update "true"; in libraries seems to be ignored.

**Comment by joemfb** [comment]
I agree that it's nonintuitive, maybe we should update `deploy/sample/rest-ext.sample.xqy` to include the annotation.

**Comment by heelix** [comment]
What is in dev is exactly what I was hoping to see.  Ty.

**Comment by grtjn** [comment]
Sorry! ;-)
