### ISSUE TITLE
Roxy with RXQ for REST API 

### ISSUE THREAD

**Issue by guru2228** [marklogic/roxy#507]
Hi,
The project is created using Roxy as REST project and we are using RXQ to expose our XQuery Functions as REST APIs using the Rewriting Capabilities from RXQ using XQuery 3.0 Annotations.
When we deploy our modules, the below error is thrown out, but the modules are deployed and the application works perfectly. Can you please guide us how to resolve the issue. Because of this error our continuous integration build is failing. Our Build is based on Maven

![capture-roxy](https://cloud.githubusercontent.com/assets/929441/9533606/c9a4ea90-4cd8-11e5-8b98-5d4d5f8eaf73.PNG)

Maven POM for the reference. We commented out because of the above issue. 
![capture-pom](https://cloud.githubusercontent.com/assets/929441/9533675/445b8528-4cd9-11e5-9fb3-dcbaaba62107.PNG)

**Comment by grtjn** [comment]
Were changes made to `ml-config.xml` for this project? If so, can you highlight the changes? And can you share the output of `./ml local info` (anonymized if you like)..

**Comment by dmcassel** [comment]
You said the project uses --app-type=rest, but you're also using your own code for RESTful APIs. Does that mean that you are not intending to use the MarkLogic REST API? By using --app-type=rest, Roxy assumes that it will find a rest-api directory with some things to deploy in it. The error came from trying to deploy rest-api/config/properties.xml. 

If you don't want your application server to host the MarkLogic REST API, switch app-type to "bare" in build.properties.

**Comment by grtjn** [comment]
I guess we are talking about this project: https://github.com/xquery/rxq

Yes, using bare app-type makes most sense for this. The Roxy rest app-type is meant for working against the MarkLogic REST api, that comes with its own rewriting.

**Comment by grtjn** [comment]
Does bare type work for you @guru2228?

**Comment by guru2228** [comment]
Yes it would work
