### ISSUE TITLE
Could not create a Roxy.jar 

### ISSUE THREAD

**Issue by damianfabian** [marklogic/roxy#509]
Hello, 

I have installed JRuby, Warbler and Ruby 1.9.7, when I tried to execute the command "ml jar" it throw me an error saying that I need to have install Ruby. if I run "jruby ml jar" I get the same error, if I added the Ruby path to my console temporally, It throw me a message saying that I need to install JRuby. 

I'm running this in a Windows machine with a strong firewall system, so I installed all the gems using --force --local. Any idea how could I solve this problem?

**Comment by grtjn** [comment]
Fixed in dev
