### ISSUE TITLE
xdmp:set-response-code does not seem to work with ML 8.0-3

### ISSUE THREAD

**Issue by heelix** [marklogic/roxy#511]
Seems like xdmp:set-response-code does not do anything anymore.  Exceptions (real ones) seem to get forwarded, but if I try to manually set a response code, it still comes back as 200/OK.

declare 
%roxy:params("")
function cs:delete(
    $context as map:map,
    $params  as map:map
) as document-node()?
{
  map:put($context, "output-types", "application/xml"),
 xdmp:set-response-code(501, "Not Implemented"),
  document { "DELETE called" }
};

I see the docs for the ML REST client show something like this now. 

http://docs.marklogic.com/guide/rest-dev/extensions#id_31884

declare function example:put(
    $context as map:map,
    $params  as map:map,
    $input   as document-node()*
) as document-node()?
{
    ...
    map:put($context, "output-status", (201, "Created"));
};

**Comment by dmcassel** [comment]
Are you saying that the output-status part does work but xdmp:set-response-code() does not?

**Comment by heelix** [comment]
Yup.  You see 'DELETE called', with 200/OK rather than the 501/Not Implemented.

**Comment by dmcassel** [comment]
Okay. Looks like our extension template needs an update.

**Comment by heelix** [comment]
That is enough to close the issue with ML8.0-3.  Probably want to have something more with fn:error() later on rather than xdmp:set-response-code... but... xdmp:set-response-code will indeed set the code/message.
