### ISSUE TITLE
Read json env properties

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#515]
Latest changes to slush-marklogic-node have introduced a generic {env}.json properties file to be used by various processes. Would be very convenient if Roxy would use those properties if present for overriding properties. Should be stronger than local.properties, though a warning might be nice if both local.json and deploy/local.properties exist.

Note: the json properties will be in the project root, not inside deploy/..

**Comment by rlouapre** [comment]
It seems to be confusing.
Why would you change Roxy to accommodate slush-marklogic-generator when it is already possible to pass variable from the command line?

**Comment by grtjn** [comment]
No, Roxy won't be accommodating slush-marklogic-node, just include reading its settings as part of config options. Otherwise you would either always have to keep local.json and deploy/local.properties in synch (error prone), or add override params for every Roxy command (even worse).

The generator will only make one call to Roxy, to generate the base project skeleton. After it is done, you run Roxy commands without Slush or Glulp in between..

**Comment by joemfb** [comment]
Wasn't there an issue or PR to add JSON/XML output to `./ml $ENV info`? That seems like a better solution; then slush or any other project could consume Roxy settings without Roxy needing to know about it or change.

**Comment by grtjn** [comment]
The aim is to have one central location for configuration. Reading Roxy properties won't help that..

**Comment by joemfb** [comment]
What properties were being duplicated across slush / roxy? Anything besides port / hostname?

In other words, couldn't slush read roxy properties, and then have it's own configuration? It makes sense to have slush-specific config separate from roxy, as opposed to inverting things and having roxy read slush's config ...

**Comment by grtjn** [comment]
They are not roxy- nor slush-specific, that is the whole point..

**Comment by joemfb** [comment]
I've they're not specific to either project, but needed by both, wouldn't reading Roxy properties solve this simply? The config is already needed by Roxy, so slush could just piggyback and read the environment-specific values.

**Comment by grtjn** [comment]
no, there is stuff beyond either, that is why I encouraged using a new location central to all..

**Comment by dmcassel** [comment]
Sorry for coming late to this, but I'm not in favor of introducing (yet) another config file that Roxy will read. People already find the three levels (default, build, {env}) confusing; I predict this would make it worse. 

Looking at the PR, the only property shown in the comments that Roxy doesn't use is node-port. For the Slush generator, it wouldn't both me if that property got put in Roxy's properties (as the single owner of configuration) and gulp used JSON output from `ml {env} info`. I don't think this PR benefits *Roxy* and would make configuration more confusing. From the discussion I see above, I vote to close.

**Comment by grtjn** [comment]
I would agree if Roxy would stand on its own, but it is being used more and more in context of a Slush project. That already adds several more config files to consider. The PR will actually make it possible to _reduce_ the number of overall config files, and make Roxy leverage config files that would exist in Slush context anyhow. It can be seen as a replacement of local.properties, but only in context of a Slush project, which is more JS/JSON centric anyhow.

We could have Slush read the Roxy configs, but to me it makes less sense to have Slush depend on a Roxy config, than have Roxy depend on a generic json config living in the project root..

**Comment by dmcassel** [comment]
Slush is not the predominate use case, and I don't think it will be (understanding that the Vanguard Team's use may be different). Roxy has and continues to be used on projects that are not related to the Slush plugin. 

I think what you're seeing is a mismatch between how Gulp projects typically handle configuration versus how Roxy does so. I think the Slush plugin would actually be better served by something Gulp/Node.js centric, such as [mlsound](https://github.com/miguelrgonzalez/mlsound) if it were further along. Roxy already has trouble with people understanding how the three levels of config files work together. I don't think changing Roxy in this way to suit the Slush plugin makes sense.

**Comment by paxtonhare** [comment]
I'm in agreement with @dmcassel . Slush is an edge case. While Vanguard uses it heavily it's only a small part of the ecosystem.

**Comment by grtjn** [comment]
Pity, this could be seen as a chance to appeal more to the JS people. But okay, if you feel local.json is too Slush specific (which was not intended that way), then this passes over..
