### ISSUE TITLE
Don't replace README when upgrading..

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#519]
Not really a bug, but a request to not update README when running `ml upgrade`. The slush-marklogic-node project puts in its own copy of a README, and would be nice if that would survive an upgrade.

Any objections?

**Comment by dmcassel** [comment]
I wonder how practical it would be to check whether the README has changed and only replace it if it has not. Probably not practical.

**Comment by grtjn** [comment]
You would only be able to compare it with the README you pulled down with upgrade, and if that is the same, you don't need to write either.. :)

You could consider comparing with the timestamp of another Roxy file that won't likely get touched. Version.txt perhaps. But I'd say, easiest to just skip it in general. It will very likely be customized for project-specific purposes..

**Comment by grtjn** [comment]
I took a closer look at the upgrader, and according to the code it wouldn't copy the README at all. Bit weird. I was sure I somehow noticed a Roxy README in a Slush generated project. I'll run some explicit tests to verify..

**Comment by grtjn** [comment]
Cannot reproduce. Could I have terminated the Slush generator before it put the Slush README in place?

Anyhow, closing ticket..
