### ISSUE TITLE
Suggestion: clean -> clear

### ISSUE THREAD

**Issue by Thijxx** [marklogic/roxy#533]
We 'clear' a database and not 'clean' it. It's not dirty after all ;)
I suggest changing the ./ml local clean to ./ml local clear because MarkLogic uses clear in admin console and in xdmp:forest-clear etc.

**Comment by grtjn** [comment]
Should be easy to support both in same way. I personally like clear better over clean as well.

**Comment by dmcassel** [comment]
While "clear" is the term used in MarkLogic's built-in functions, Roxy's had "clean" for about four years now. I wouldn't change it, but I wouldn't object to supporting "clear" as a synonym either. This (and any other synonym) can be done with app_specific.rb as well.

**Comment by grtjn** [comment]
This is probably a oneliner, pushing away nonetheless, sorry..
