### ISSUE TITLE
Roxy deployer using admin externally Authenticated using LDAP -

### ISSUE THREAD

**Issue by guru2228** [marklogic/roxy#550]
Hi Team,
We have an external authentication setup for our application residing in Marklogic and we defined a role called roxy_deploy which is tied to an LDAP Group and a LDAP User is associated with this role. The role has all the required privileges to run Roxy. The problem is when we use the user who is authenticated using the LDAP, we are not able to use Roxy deployer to deploy the code, data, or clean up the code or content database. We are getting the error as 

![roxy-issue](https://cloud.githubusercontent.com/assets/929441/10950202/3b625fec-82fc-11e5-9d56-0f81166843a2.PNG)

Could you please guide me how to resolve. I doubt the problem is with bootstrap port. Could you please help us what are the per-requisities to use Roxy with external authentication for the admin user who is being authenticated against the LDAP

**Comment by jmeekhof** [comment]
Guru,

The problem most likely is with the bootstrap port. The admin, app services, and query console all should use internal authentication as they don't play well with LDAP. Try executing with -v and see which port you're actually accessing.
`ml stage deploy src -v`

In my experience, you'll need a Mark Logic native user to execute the deploy tasks using Roxy.

**Comment by grtjn** [comment]
As Josh suggests, Roxy makes a lot of different calls, often to qc eval, and appservices as well as to the app specific ports, even when executing just one user command. If you set user/password to your ldap user only the calls to the one app server with external auth will succeed. We have plans to provide separate user/pass props for each type of ports, but that work hasn't been started yet.

Note also that deploy src only hits the xcc-port. Deploy rest also hits the app-port. Not sure if you enabled external auth for both servers..

**Comment by guru2228** [comment]
Hi Josh and Greet,

Yes the problem is with the bootstrap port (refer the below screenshot). I very much have the doubt that whether our DBA  team will allow to use native (Internal)  user to execute the tasks using Roxy.

What are the options available for us in this case. Can you please suggest your recommendations

![roxy-issue-1](https://cloud.githubusercontent.com/assets/929441/10951976/e24108be-8305-11e5-9234-d049340a0b1d.PNG)

**Comment by grtjn** [comment]
I think easiest way out would be to duplicate qc and appservices app servers, and put external auth on them. Then try if your roxy user has sufficient rights to access these. You should only need read access for /v1/manage..
