### ISSUE TITLE
Deploy only newer content

### ISSUE THREAD

**Issue by nespera** [marklogic/roxy#551]
We have a change locally that allows the passing of a command line flag to "ml deploy content" so that it will only deploy files which are new or have a more recent modification date than the equivalent on the server (using document timestamp). We have found this useful when the deployed content is a set of "baseline" documents that can be modified in a running system.

Is this change something that is likely to be merged if turned into a Pull Request?

Thanks

Chris

**Comment by grtjn** [comment]
I'd be interested!

**Comment by dmcassel** [comment]
I think it would be most helpful in the local environment (where you're the only one deploying), but yeah, a number of people have asked about a capability like that. Very welcome, especially as an option. 

Might also be interesting if controllable from a property. Then I can set it up such that I get quick deploys locally and complete deploys to remote environments, and I get that without having to use a flag each time.

**Comment by grtjn** [comment]
Looks like this is fixed in dev now. Just wondering, since load_data was changed, does this now work on deploy modules and deploy schemas as well?

**Comment by nespera** [comment]
No, I don't think that will work. But it shouldn't be a big change if someone was interested in extending it to do that.

**Comment by grtjn** [comment]
It is actually very close. All load_data calls include a dest db in the options. Only the get_db_timestamp needs a change to receive, and use that dest db to pull timestamps from..
