### ISSUE TITLE
Configuring Roxy for Unit Testing in ML8

### ISSUE THREAD

**Issue by jeet1212** [marklogic/roxy#563]
Hi,

I was testing Unit Tests feature of the Roxy for my project however no success.I am using roxy as MVC not hybrid. I am testing it in ML8.

When I invoked url http://localhost:8042/test, started seeing below error.
error in /roxy/rewrite.xqy line number 40, conf:rewrite() function not found.

else
    try
    {
      xdmp:eval('
        import module namespace conf = "http://marklogic.com/rest-api/endpoints/config"
          at "/MarkLogic/rest-api/endpoints/config.xqy";
        declare variable $method external;
        declare variable $uri external;
        declare variable $path external;
        (conf:rewrite($method, $uri, $path), $uri)[1]',
        (xs:QName("method"), $method,
         xs:QName("uri"), $uri,
         xs:QName("path"), $path))
    }
    catch($ex) {
      if ($ex/error:code = "XDMP-MODNOTFOUND") then
        $uri
      else
        xdmp:rethrow()
    }

Also some of the default UTs are not running due to URI security privileges.

Please let me know if I am missing for providing appropriate privileges to the default user.

Regards,
Indy

**Comment by RobertSzkutak** [comment]
It's a known issue that rewrite.xqy is broken in Roxy in MarkLogic 8.0-2 and up. Depending on which version you're running, there are some workarounds in this thread: https://github.com/marklogic/roxy/issues/416

**Comment by jeet1212** [comment]
Thank you for sharing it however it seems there are security privileges for
default user as well.

I noticed that the default user should have xdmp:eval,  eval-in and uri
privileges.

Please suggest if I am missing something.

Regards,
Indy

**Comment by dmcassel** [comment]
There are several missing privileges that prevent the app-user from being able to run the built-in unit tests. I'm exploring the best way to fix that.

**Comment by dmcassel** [comment]
Took me a while to get to this, but I just [submitted a PR](https://github.com/marklogic/roxy/pull/674). Reviews welcome.

**Comment by dmcassel** [comment]
fixed in dev
