### ISSUE TITLE
SEC-ROLEDNE: Role does not exist: sec:role-name = rest-extension-user

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#564]
I tried deploying modules on a ML6.0-6 server but I got the SEC-ROLEDNE error on the rest-extension-user role.
I'm using the 1.7.3-dev branch of ROXY and in the file server_config.rb on line 1565 there is a block of code stating that this should work for MarkLogic 6+
But the role rest-extension-user is NOT present when you do a clean install of ML6.0-6

Temporary work around is to just create the role.

**Comment by grtjn** [comment]
Peet refers to https://github.com/marklogic/roxy/blob/v1.7.3/deploy/lib/server_config.rb#L1681, but that comment is invalid unfortunately. That role was not introduced until MarkLogic 7.

To use Roxy with MarkLogic 6 or 5 it is advised to downgrade to v1.7.0. You can do that using `./ml upgrade --branch=v1.7.0`. (If upgrader chokes on a missing CHANGELOG.mdown, rename CHANGELOG.md to .mdown)

**Comment by grtjn** [comment]
Closing this ticket..
