### ISSUE TITLE
How to set "update-policy" property throught Roxy

### ISSUE THREAD

**Issue by romain-nio** [marklogic/roxy#569]
Hi,

I'm wondering if it's possible to set the "update-policy" property directly throught Roxy. I'm able to set it thourght API but I don't know how to do it with Roxy.

Thanks,
Romain.

**Comment by grtjn** [comment]
If you mean `assignment-policy` on databases, then afraid not. I did see it when going through properties added in ML8, but this required a little more effort, not a straight-forward value assignment. Shouldn't be too difficult though, we have dealt with other properties that are similar in complexity..

**Comment by grtjn** [comment]
Sorry, pushing away to allow release of 1.7.3..

**Comment by rlouapre** [comment]
This is for optimistic locking. I think it is already possible [1]

Just add it in roxy/rest-api/config/properties.xml:

```xml
...
<update-policy>version-optional</update-version>
...
```

Assuming rest-* properties are correctly set ```deploy rest``` or ```deploy modules```

[1] - https://github.com/marklogic/roxy/wiki/REST-properties-format-change

**Comment by grtjn** [comment]
Ah thnx, here the DMC docs on REST properties: http://docs.marklogic.com/REST/GET/v1/config/properties/[property-name]#config-properties

**Comment by dmcassel** [comment]
I just sent a PR that adds this property to the sample properties, so that it will be present in the file and easier to edit.
