### ISSUE TITLE
Toggling the Run/Run All Tests checkboxes don't update the active styling for tests

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#570]
## Overview

For both the Test Suite and tests for a given test suite lists, toggling the Run/Run All Tests checkbox does not toggle the active state for the affected items (test suites and tests respectively). They are toggled when using the per-item checkboxes.

## Use Case

As a user running roxy-based unit tests, I want to easily see which tests will be run using the "Run Tests" button.

## System

Roxy Version: 1.6
Operating System: Windows
Web Browser: Firefox

**Comment by dmcassel** [comment]
Hi @rhdunn. Looking at the "Framework Tests" suite as an example, if you uncheck the top-level checkbox, the individual test checkboxes don't change, but that suite will not be run when you click "Run Tests". If that top-level checkbox is checked, any selected tests under that suite will be run. 

I get what you're saying, that you anticipated that the individual test check boxes would get cleared when a suite's checkbox gets unchecked. I think that the original intent was that you could select some tests within a suite, and then checking or unchecking the suite-level box would preserve your choice, while still controlling whether that suite was run. (sound right, @paxtonhare?) With that in mind, I think the top-level checkbox *does* easily show which test suites will be run. 

Further comments welcome.

**Comment by rhdunn** [comment]
I don't mind (and like) preserving the checkbox state. I am referring to the CSS used to make checked items black and unchecked items gray -- that logic does not match the checkbox state.

**Comment by dmcassel** [comment]
Ah, I see what you mean. Thanks for clarifying.

**Comment by dmcassel** [comment]
fixed in dev
