### ISSUE TITLE
The active styling is not set correctly when first loading the page for unchecked tests/test suites

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#571]
## Overview

When loading the unit test driver page, the checkboxes for the active Test Suites and tests within each test suite are checked or unchecked according to their previous selection, but the unchecked Test Suites and tests are not given the inactive (grayed out) styling used when deselecting a Test Suite/Test.

## Use Case

As a user running roxy-based unit tests, I want to easily see which tests will be run using the "Run Tests" button.

## System

Roxy Version: 1.6
Operating System: Windows
Web Browser: Firefox

**Comment by dmcassel** [comment]
Reproducible in Firefox. Interesting, Chrome just resets all selections (test: load test page; uncheck some tests; hit refresh).

**Comment by dmcassel** [comment]
fixed in dev
