### ISSUE TITLE
Exceptions within the setup/teardown files are not displayed when running a test suite.

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#573]
## Overview

If a test suite setup/teardown file contains syntax errors, logical errors (e.g. cast errors), or other errors running that test suite displays a "NO TESTS RUN" message.

## Use Case

As a developer, I want to see any exceptions in setup/teardown code within the test runner UI so I can easily identify and fix problems in the setup/teardown code (e.g. like exceptions that occur when the test files contain syntax or logical errors).

## System

Roxy Version: 1.6
Operating System: Windows
Web Browser: Firefox

**Comment by dmcassel** [comment]
fixed in dev
