### ISSUE TITLE
ml local deploy modules throwing error

### ISSUE THREAD

**Issue by ShabKhan** [marklogic/roxy#575]
Hi,
When I tried simple acceptable deploy command :
ml local deploy modules it is throwing error :
![image](https://cloud.githubusercontent.com/assets/17489454/13461889/6207e93a-e0aa-11e5-861a-4991e63244c2.png)
As suggested by David I checked the value of **load-html-as-xml** that is false only.
I am using ML-8.
Can anyone help?

**Comment by grtjn** [comment]
Adding -v might reveal which file is causing trouble. You could also try upgrading to dev with `./ml upgrade --branch=dev`.

**Comment by dmcassel** [comment]
@ShabKhan has not replied to @grtjn's suggestion, so I'm going to close this for now as unreproducible. @ShabKhan, if you're still experiencing this error, please run

    ml local deploy modules -v

and let us know what additional output you get.
