### ISSUE TITLE
How to set S3 credentials property throught Roxy

### ISSUE THREAD

**Issue by romain-nio** [marklogic/roxy#581]
Hi,

I'm using marklogic 8 and S3 for my scheduled backups.

I'm wondering if it's possible to configure AWS S3 crendentials (access key + secret key) directly through Roxy ?

I only found the way to configure this settings manually in the admin : 
og into the Admin Interface.
Click Security icon on the left tree menu.
Click Credentials to open the Credential Configuration page.
Enter the aws access key and aws secret key provided for your AWS account.

Thanks

**Comment by grtjn** [comment]
Fixed in dev..
