### ISSUE TITLE
Space in Ruby Path causes ml.bat to fail

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic/roxy#601]
After doing Roxy upgrade to 1.7.3 master the ml.bat script fails in windows.

C:\EDH_ML_Path4_3\eie_edh_framework\EDH_ML>C:\Program Files (x86)\Ruby21\bin\rub
y.exe -Ideploy -Ideploy\lib deploy\lib\ml.rb
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dmcassel** [comment]
I don't have a Windows setup handy. @rjkennedy98 could you run a quick test? In [ml.bat, line 12](https://github.com/marklogic/roxy/blob/master/ml.bat#L12), add quotes around the value for RUBYFOUND, so that it looks like this:

    set RUBYFOUND="%%~$PATH:X"

If that works, we can update the script. If not, I invite input from someone with more Windows scripting fu than I have.

**Comment by rjkennedy98** [comment]
That gave me:
C:\EDH_ML_Path4_3\eie_edh_framework\EDH_ML>ml local deploy modules
'""' is not recognized as an internal or external command,

I have made a change ml.bat, line 158
  "%RUBYFOUND%" -Ideploy -Ideploy\lib -Ideploy\test deploy\test\test_main.rb

and ml.bat, line 167
 "%RUBYFOUND%" -Ideploy -Ideploy\lib deploy\lib\ml.rb %*

that seemed to resolve issue

**Comment by rlouapre** [comment]
I am not sure we should have provided a fix for it...
Screen from Ruby installer:
![image](https://cloud.githubusercontent.com/assets/6400566/15516773/5f9d7abc-21c2-11e6-88e4-8a826990ae67.png)
It clearly says "please avoid any folder name that contains spaces"

**Comment by dmcassel** [comment]
@rlouapre interesting find. While I agree with you -- the instructions are pretty clear -- it's a pretty simple fix for Roxy. Might as well.

**Comment by rjkennedy98** [comment]
The client I am working with has managed VMs which have a space in the ruby install path. Otherwise, yes, it could be easily avoided by following directions.

**Comment by grtjn** [comment]
Fixed in dev..
