### ISSUE TITLE
Move Roxy off Query Console endpoint

### ISSUE THREAD

**Issue by clockworked247** [marklogic/roxy#612]
Roxy should be using the /v1/eval endpoint instead.  ML 9 will add deeper security to QC endpoints, no longer allowing for Roxy or any other unauthorized requestors to use them.

**Comment by dmcassel** [comment]
+1 on this. We can probably do it for ML8 as well, since that's when the endpoint became available.

**Comment by grtjn** [comment]
Fixed in dev..
