### ISSUE TITLE
Roxy deployer failing After upgrade

### ISSUE THREAD

**Issue by abhishek-cognizant** [marklogic/roxy#618]
Hi Group, After ML upgrade from 7.x to 8.x, Roxy deployer is failing with exception 404 "Not Found". Is there any way to patch Roxy rather taking complete new Roxy version

**Comment by dmcassel** [comment]
Yes. There are two things you should probably do:

1. Use the "ml upgrade" command. See "ml upgrade -h" for more info. 
2. Update the `server-version` property in deploy/build.properties from 7 to 8

**Comment by abhishek-cognizant** [comment]
Thanks, I am getting following error while running "ml upgrade". Please advise


ERROR: Missing branch name
Usage: ml upgrade --branch=[dev|master]
  Upgrades Roxy files in the current project, using files from the
  specified branch on GitHub. Any project will have its deploy directory
  upgraded. Projects of app-type "mvc" or "hybrid" will also have their
  src/roxy/ directory upgraded.

branch: (required)
  The name of the Roxy GitHub branch to use for the upgrade.

**Comment by grtjn** [comment]
Use `ml upgrade --branch=master`..

**Comment by abhishek-cognizant** [comment]
It is throwing below error while upgrade from master.
ERROR: No such file or directory @ rb_file_s_stat 

I am thinking may be issue is different, Any change in url-rewriter that can cause this issue? XQuery modules are getting loaded to the database but while loading Rest extensions Roxy deployer is failing.

**Comment by RobertSzkutak** [comment]
Are you using a REST application? The rewriter for that is now /MarkLogic/rest-api/rewriter.xml (it used to be *.xqy in ML7).

**Comment by abhishek-cognizant** [comment]
Wow! that worked, thanks a lot!!!

**Comment by grtjn** [comment]
Yes, that should help. Latest Roxy would fix on the fly for you though.

Not sure why the upgrade fails. That is not related to MarkLogic..
