### ISSUE TITLE
How to use ML variable in env properties file

### ISSUE THREAD

**Issue by romain-nio** [marklogic/roxy#619]
Hi,

I added the following ML Roxy function (cf [here](https://github.com/marklogic/roxy/wiki/Using-Operating-System-Environment-Variables-in-properties))  to be able to retrieve variable from my env variables (eg : env variable "ml_password=13456"). It works, I'm able to read them with "./ml dev info" :
Assign value :
```
$ export ml_password="123456"
```
Test :
```
$ ./ml dev info
IS_JAR: false
Properties:
ml.user: casper
ml.password: 13456
```

 I want to use "ml.password" in my **Roxy/deploy/dev.properties** env file to hide my password but I'm not able to do it. I tried the following code :
```
dev-server=X.X.X.X
user=casper
password=@ml.password
```

If I try a bootstrap, it failed :
```
Deploying Bootstrap..
Bootstrapping your project into MarkLogic 8 on X.X.X.X..
ERROR: Invalid login credentials for dev environment!!
```

Any idea ?

**Comment by grtjn** [comment]
I think that wiki page is a little outdated. You don't need to do anything anymore. The following line in server_config.rb will always look for `ml_{propname}` in ENV:

https://github.com/marklogic/roxy/blob/master/deploy/lib/server_config.rb#L2157

E.g. just make sure you add `password=` to your dev.properties, and then provide the override via environment, and it should work..

PS: you can also override vars via command-line with `--ml.password=pwdoverride`. Command-line works strongest, then env, then env properties, then build properties, then default properties..

**Comment by romain-nio** [comment]
THanks for your answer ! I tried to add the code you mentionned in my server_config.rb but it's not working... Not a big deal because your other solution is very good : "you can also override vars via command-line with --ml.password=pwdoverride"

I'm able to send my password and mu user with this "command-line" way, but I'm not able to send other argument. Example with this ml-config :
```
        <user>
            <user-name>toto</user-name>
            <description></description>
            <password>@ml.totopwd</password>
            <role-names>
                <role-name>admin</role-name>
            </role-names>
            <permissions/>
            <collections/>
        </user>
```
and with the following command :
`./ml $env bootstrap --ml.password=${MARKLOGIC_ADMIN_PASSWORD} --ml.user=${MARKLOGIC_ADMIN_USERNAME} --ml.totopwd=${MARKLOGIC_ADMIN_USERNAME}
`

I have the following error: 
`W, [2016-06-15T09:43:21.390333 #2427]  WARN -- : Property ml.totopwd does not exist. It will be skipped.`

**Comment by grtjn** [comment]
The code i was referring to is in master branch. Can you use ml upgrade?

You can only override what exists in a properties file. Define totopwd in build properties, and leave blank or give it a default value..

**Comment by romain-nio** [comment]
perfect thanks  @grtjn :)
