### ISSUE TITLE
ERROR: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#620]
Running `ml dev info` when `deploy/dev.properties` does not exist results in `ERROR: no implicit conversion of nil into String`. Line 131 of `server_config.rb` should read:

```
        logger.info k + ": " + v.to_s
```

(e.g. with an extra `.to_s` after v)

**Comment by grtjn** [comment]
Note: `ml dev info --format=json` works fine..

**Comment by grtjn** [comment]
PS: my impression was that it breaks on `ml.server` being not properly set..

**Comment by RobertSzkutak** [comment]
Looks like a duplicate of issue #224

**Comment by dmcassel** [comment]
fixed in dev
