### ISSUE TITLE
Passwords not bootstrapped correctly

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#621]
appuser-password values containing `{` or `}` or `\` get mangled.

The first two are doubled, by changes I made myself, though I don't really see how it breaks exactly, see end of build_properties?

The latter just disappears, taking along the following character (if any?). Happens because gsub interprets replacement, and \ has special meaning. Tried to escape, but that didn't seem to help..

**Comment by dmcassel** [comment]
fixed in dev
