### ISSUE TITLE
Minimum Permission for deployment

### ISSUE THREAD

**Issue by kgcprakash** [marklogic/roxy#624]
Hi, How to get / find out the minimum privilege/permission required for the ml-user performing marklogic deployment via roxy tool. (in other words; the user performing marklogic deployment using roxy tool; should that user have to be an admin user (always)).

**Comment by RobertSzkutak** [comment]
To be clear, are we talking about source code deployment (./ml ENV deploy src/modules/rest) or infrastructure deployment (bootstrapping)? (./ml ENV bootstrap)

**Comment by kgcprakash** [comment]
Am setting up an user for performing marklogic deployments via roxy. I don't want to give a user with admin role to deployment team. So wanted to setup a user; that has minimum required roles / privileges for performing deployment - like modules, content, schema deployment (i assume bootstrap will require admin role as it is connecting to admin ports)

**Comment by grtjn** [comment]
Related to #600, #491, and #438..

**Comment by grtjn** [comment]
Deploy src uses XCC, and requires xdbc related privileges, and probably also any-uri. Deploy rest is slightly different, as that goes through REST-api. You need rest-admin role, and/or rest-writer priv + any-uri priv probably..

+1 on documenting this, +10 on providing sample users/roles for this..

**Comment by grtjn** [comment]
See also #491, and #600

**Comment by grtjn** [comment]
Covering this in #600.
