### ISSUE TITLE
ADMIN-INVALIDCONFIG: (err:FOER0000) after updating Roxy to 1.7.3

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#625]
I am getting:

    ERROR: ADMIN-INVALIDCONFIG: (err:FOER0000) Invalid configuration: XDBC servers do not support application-level authentication

after upgrading to `v1.7.3` on MarkLogic 8.0-4.2. It works with `v1.7.2` without generating an error.

I've tracked this down to commit e33b3c54061f45b087ab9085b769dacabee71b6f ("Fixed #469: moved config snippets into overridable functions") using `git bisect`.

The MarkLogic ErrorLog.txt places the error in the call to `admin:appserver-set-authentication` at line 10847 of `/MarkLogic/admin.xqy`.

**Comment by grtjn** [comment]
Yeah, we introduced the option to specify auth-method for XDBC servers in there. I recommend adding an `xdbc-authentication-method=digest` line to your build.properties.

We might need to consider adding that as default to defaults.properties. @dmcassel WDYT?

**Comment by rhdunn** [comment]
Adding that line to `build.properties` fixes the bootstrap error. Thanks.

**Comment by dmcassel** [comment]
+1 to adding xdbc-authentication-method=digest to default.properties.

**Comment by RobertSzkutak** [comment]
Was fixed in PR #646
