### ISSUE TITLE
Unit-Test interface missing

### ISSUE THREAD

**Issue by Thijxx** [marklogic/roxy#637]
Following the tutorial by David here: https://www.youtube.com/watch?v=PDiGN2ZYmQQ
After bootstrapping & deploying modules, there is no Test interface on the supposed URL.
This is what I get:

```
XML Parsing Error: no element found
Location: http://localhost:8742/test/
Line Number 1, Column 1:
```

I run 8.0-4.2 and the app-type is REST.

**Comment by rhdunn** [comment]
You need to run the modules from the filesystem in order to access the Roxy tests in /test.

1.  Select the registered server in the `Groups > Default > App Servers > [Your Server Name]` section of the admin UI (typically on port 8001).
2.  Set the `root` to be the location of your Roxy `src` folder.
3.  Set the `modules` to be `(file system)`.

**Comment by Thijxx** [comment]
By 'the registered server', do you mean the '-test-' database HTTP server ROXY creates for testing purposes?
Does the root need to be set to the absolute path to the src folder on the server?
Have tried the above but the message stays the same.

**Comment by rhdunn** [comment]
By "the registered server" I mean the server from the `app-name` in your deploy properties file.

The root needs to be set to the absolute path to the src folder on the server. Relative paths may work, but I don't know what path they are relative to.

**Comment by Thijxx** [comment]
Thanks. I rather not change the configuration of my database for the sake of unit-tests. My modules are in the Modules database now and I like to keep them there.

**Comment by rhdunn** [comment]
You can also configure the `test-content-db`, `test-modules-db` and `test-port` configuration properties on your test server where you can also access '/test'. You can put these in a `dev.properties` file that is separate from your `prod.properties` production file.

**Comment by Thijxx** [comment]
great idea, thanks! I think the configuration is good this way. now I think I'm missing the unit-test files.. in the Youtube tutorial, some kind of interface is show. I expect ROXY to create the necessary files when it noticed I use the `test-` settings. But `/src` stays empty

**Comment by dmcassel** [comment]
A couple notes:

- You do not need to use the filesystem to make use of unit tests -- using the modules db is fine. You do have to run "deploy modules" if you use a modules database. 
- Be aware that the default configuration automatically excludes tests from being deployed to production. 
- In the video, I didn't specify an --app-type with the "ml new" command. I believe the default is still to build an MVC application, which comes with source code for that stuff as well as for the unit testing. However, if you specify --app-type=rest, most of that code is irrelevant, so you start with an empty src directory. You'll need to copy the unit testing files from another copy of Roxy. I've added a link to the Unit Testing wiki that points to the [Unit Testing REST Applications wiki](https://github.com/marklogic/roxy/wiki/Unit-Testing-REST-applications) to make this easier to find.
