### ISSUE TITLE
The get-test-file/get-module-file test methods force returning unquoted documents.

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#638]
The `helper:get-modules-file` method called via `helper:get-test-file` has the following behviour:

1.  It loads the local files as text, then forces it through `xdmp:unquote`, hiding any errors (e.g. malformed XML).
2.  It forces text documents loaded from the modules database through `xdmp:unquote`, hiding any errors like with the local file code path.

This makes it difficult to load files in a specific format (XML documents as plain text, binary documents, etc.) for use in tests.

The swallowing of errors in `xdmp:unquote` hides potential issues, such as mismatched XML tags in an XML document, making it difficult to catch these errors when running the tests locally.

**Comment by dmcassel** [comment]
fixed in dev
