### ISSUE TITLE
Support SJS controllers

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#640]
ml extend only supports xqy extensions, and samples doesn't include sjs samples either..

**Comment by prestonmcgowan** [comment]
/app/config/config.xqy
`
<request uri="^/api/print/here$" endpoint="/roxy/query-router.xqy">
	<http method="GET"/>
	<uri-param name="controller">test</uri-param>
	<uri-param name="language">sjs</uri-param>
	<uri-param name="func">print</uri-param>
	<uri-param name="format">json</uri-param>
</request>
<request uri="^/api/compute/area/(\d+)$" endpoint="/roxy/update-router.xqy">
	<http method="PUT"/>
	<uri-param name="controller">test</uri-param>
	<uri-param name="language">sjs</uri-param>
	<uri-param name="func">width</uri-param>
	<uri-param name="width">$1</uri-param>
	<uri-param name="format">json</uri-param>
</request>
`

/app/config/controllers/test.sjs
`var req = require("/roxy/lib/request.xqy");

module.exports = {

	print : function () {
		var rqst = xdmp.getRequestBody().toObject();
		xdmp.log(rqst.here);
		return "here";
	},
	area  : function () {
		var width = req.get("width");
		return width * width;
	}
};
`

I also have the test.sjs dumping the HTTP Request Body to show how you could get at the full contents of the request.
