### ISSUE TITLE
Unit Test - TOOMANYARGS

### ISSUE THREAD

**Issue by Thijxx** [marklogic/roxy#641]
When making unit tests, I run into the following; here the first case passes but the second fails. This is copy/pasted from examples provided within the ROXY repo.
What's up with the arguments here?!

```
import module namespace test="http://marklogic.com/roxy/test-helper" at "/test/test-helper.xqy";

declare function local:case2()
{
  test:assert-true(fn:false())
};

(: success :)
test:assert-throws-error(xdmp:function(xs:QName("local:case2")), "XDMP-TOOMANYARGS"),

(: fail :)
test:assert-throws-error(xdmp:function(xs:QName("local:case2")), "ASSERT-TRUE-FAILED")
```

**Comment by grtjn** [comment]
Which version of MarkLogic are you using exactly? Sounds fishy..

@dmcassel you any thoughts on this? I'm less familiar with the test framework..

**Comment by bradmann** [comment]
I'm seeing the same behavior against ML8.0-5.5. Paging @dmcassel...

**Comment by bradmann** [comment]
cancel that call, dave. looks like this is fixed in dev. when are we gonna get the latest dev merged to master?

**Comment by dmcassel** [comment]
Sounds like this has already been addressed in dev, so I'm going to close this one. Please re-open if you're still seeing it on the dev branch.
