### ISSUE TITLE
Bootstrapping scheduled tasks doesn't work when using the filesystem

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#648]
$ ./ml local bootstrap
    Bootstrapping your project into MarkLogic 9 on localhost...
    ERROR: ADMIN-NOSUCHDATABASE: (err:FOER0000) No such database filesystem
    See MarkLogic Server error log for more details.
    ERROR: ... Bootstrap FAILED
    ERROR: exit
    ERROR: ["deploy/lib/ml.rb:170:in `exit'", "deploy/lib/ml.rb:170:in `<main>'"]

This is because `setup:create-scheduled-task()` assumes a modules database. It's an easy fix; pull request soon.

**Comment by dmcassel** [comment]
I saw this on MarkLogic 9, but the problem is independent of the version.

**Comment by grtjn** [comment]
Fixed in dev..
