### ISSUE TITLE
rewrite.xqy does not correctly handle static files on MarkLogic 8.0

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#654]
Using 8.0-4.2, navigate to the `/test/` path. This loads the CSS, images, etc. for the test page (e.g. `/test/img/warning.png`). On my MarkLogic install, this generates:

    XDMP-UNDFUN: (err:XPST0017) Undefined function conf:rewrite()

for each of the content items, so the page loads, but the associated CSS, images and JavaScript do not. This is from:

    import module namespace conf = "http://marklogic.com/rest-api/endpoints/config"
      at "/MarkLogic/rest-api/endpoints/config.xqy";

in the `xdmp:eval` fallback to `req:rewrite` not returning a rewritten URI.

Handling this error in `rewrite.xqy` to return `$uri` fixes the problem.

**Comment by RobertSzkutak** [comment]
I'm having trouble reproducing this. I grabbed a fresh copy of the dev branch, bootstrapped and deployed, navigated to /test/ and the page appeared to load just fine. Is there another step I might be missing?

**Comment by RobertSzkutak** [comment]
I forgot to mention that this error message : `XDMP-UNDFUN: (err:XPST0017) Undefined function conf:rewrite()` suggests to me that you may not have this fix from the dev-branch in your code : https://github.com/marklogic/roxy/pull/588

**Comment by grtjn** [comment]
The rewrite issues only occur in 8.0-2 or later if i am not mistaken..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Robert Szkutak <notifications@github.com> 
Datum: 31-08-2016  14:18  (GMT+01:00) 
Aan: marklogic/roxy <roxy@noreply.github.com> 
Onderwerp: Re: [marklogic/roxy] rewrite.xqy does not correctly handle static files on MarkLogic 8.0 (#654) 
 
I'm having trouble reproducing this. I grabbed a fresh copy of the dev branch, bootstrapped and deployed, navigated to /test/ and the page appeared to load just fine. Is there another step I might be missing?

**Comment by rhdunn** [comment]
@RobertSzkutak This is fixed in #416. Feel free to close.
