### ISSUE TITLE
RFE: support more eval options in deploy/server_config execute_query()

### ISSUE THREAD

**Issue by mblakele** [marklogic/roxy#66]
When creating a deploy/app_specific.rb module to extend `ml`, it would be handy to have access to more eval options for `execute_query`. It looks like `db_name` is already supported, but a setup query might like to have access to the application code. So setting the eval module database and module root  would be useful.

**Comment by grtjn** [comment]
execute_query already supports both db_name as well as app_name. I think that should cover needs sufficiently.
