### ISSUE TITLE
*.js files loaded as binary by default

### ISSUE THREAD

**Issue by abedegno** [marklogic/roxy#662]
If I have javascript modules under src and load using:
./ml local deploy modules
The files are loaded as binary rather than text.

**Comment by grtjn** [comment]
We once added a toggle for this, but defaulted it to load as binary. I think having the default be false (let ML decide) is better: https://github.com/marklogic/roxy/issues/138

**Comment by grtjn** [comment]
Workaround for now is to add this to you env or build properties: `load-js-as-binary=false`

**Comment by heelix** [comment]
Yah, this burned us the other day when we were doing some server side
JavaScript for the SAML.  The work around worked... but it was not expected
behavior.  (Don't do a lot of server side JS, so not sure what the norm
should be)
