### ISSUE TITLE
install/uninstall commands

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#666]
Install, just as a means to group:
- bootstrap
- deploy modules
- deploy schemas
- deploy triggers
- deploy content

(missing anything?)

Uninstall, for symmetry:
- wipe

Saves step at initial ramping up, and makes automation a little easier. Using app_specific overrides, you could tap in, and extend to specific needs, like mlcp imports of content..

**Comment by RobertSzkutak** [comment]
A customer shared with me yesterday that they want this functionality.

**Comment by dmcassel** [comment]
fixed in dev
