### ISSUE TITLE
Transactional Unit Tests always succeed

### ISSUE THREAD

**Issue by Thijxx** [marklogic/roxy#667]
Following this: https://github.com/marklogic/roxy/wiki/Transactional-Unit-Tests

The unit test I run fails and created a log entry detailing this, that is correct. But ROXY does not show this test as failed, it return success.

Maybe this has something to do with the try/catch in the transactional test setup?

**Comment by dmcassel** [comment]
Verified using the second approach listed on the wiki page. The last transaction needs to return the result of calling assert in order for the results to be counted. I think the fix here will probably be to document a better way to write the test.

**Comment by dmcassel** [comment]
@Thijxx you were right, it was the try/catch. I've updated the sample code on [the wiki](https://github.com/marklogic/roxy/wiki/Transactional-Unit-Tests). Would you mind a quick review?

**Comment by Thijxx** [comment]
Works fine now with the rethrow, thanks.
