### ISSUE TITLE
Exit code on windows.

### ISSUE THREAD

**Issue by eurochriskelly** [marklogic/roxy#680]
Hi,

I ran into [an issue](http://stackoverflow.com/questions/40001140/child-process-not-returning-correct-exit-code-from-batch-file/40193695#40193695) while trying to automate roxy using nodejs. Basically, on windows, the batch file does not return the correct exit code to the program. I fixed by adding the following last line to ml.bat

exit /b %errorlevel%

Would it be possible to add this permanently?

**Comment by RobertSzkutak** [comment]
Good suggestion. Offhand, did you notice if the *.sh file returns the correct exit code? There was at least one old issue to get this right and I'd like to make sure it works in both the *.bat and *.sh. PR's welcome :)

**Comment by eurochriskelly** [comment]
Yes. *,sh version worked perfectly! I will make a PR

**Comment by dmcassel** [comment]
fixed in dev
