### ISSUE TITLE
Bootstrap does not create new self-signed certificates

### ISSUE THREAD

**Issue by kford-oconnors** [marklogic/roxy#693]
Configuring an ssl certificate in ml-config.xml inserts a template but does not create a usable certificate.

When a certificate template is created via the Admin UI, MarkLogic automatically generates a self-signed CA and certificate from the template. When a new certificate template is created via the Roxy deployer, no certificate is generated; app servers using this certificate template are not usable until the certificate is generated manually.

Steps to reproduce: 
1. Include the sample ssl certificate and an HTTP server that uses it in ml-config.xml
2. Bootstrap
3. `curl https://localhost:[app-port]` > "(35) Server aborted the SSL handshake"
4. In the Admin UI, click 'ok' on the Configure page for the new template
5. curl now returns expected result (complaint about insecure certificate)

Our workaround is a post-bootstrap custom build step that creates the certificate using pki:generate-temporary-certificate().

**Comment by RobertSzkutak** [comment]
Thanks for the PR @kford-oconnors !
