### ISSUE TITLE
How to load data into specific collection?

### ISSUE THREAD

**Issue by trekvr** [marklogic/roxy#712]
Hi,

How to load data into specific collection? tried below command but not working.

cmd:
ml local deploy content --collection=abc

Regards,
Rajesh

**Comment by dmcassel** [comment]
`--collection` is not supported on that command. You can see the options for any command by adding the `-h` flag:

    ml deploy content -h

Our recommendation is to use MLCP (`ml mlcp -h`). Note that MLCP is not included in the Roxy distribution; set the `mlcp-home` property to point to where you have MLCP installed. 

If someone wanted to add the `--collection` parameter, a PR would be welcome.

**Comment by RobertSzkutak** [comment]
Duplicate of https://github.com/marklogic/roxy/issues/106

It's definitely preferable to use MLCP, but I recognize the attractive convenience of such a feature.

**Comment by dmcassel** [comment]
closing as duplicate
