### ISSUE TITLE
Do not bootstrap MarkLogic database if configuration is already in place.

### ISSUE THREAD

**Issue by jacek-lapinski** [marklogic/roxy#714]
I find Roxy very useful. I have introduced it to my continuous integration process. Bootstrap takes some time and I would like to omit it when mlconfig has not changed since last deployment. Have you ever met with this problem? Of course I can save somewhere mlconfig after deployment and compare with it before next deployment, but I would like to find more elegant solution. Do you have any idea how to resolve this?

**Comment by dmcassel** [comment]
When I've included Roxy in CI processes in the past, I've included the bootstrap step. Yes, it takes time, but it ensures the right configuration. That said, I understand the desire to speed it up. 

Right now, we don't have a way to compare the current deployed configuration to the current configuration on disk. I guess one way to do that would be to calculate a hash of the current configuration (which would need to account for not only ml-config.xml, but the environment-specific properties as well). This hash could be stored on the server, then bootstrap could check for the hash and compare with the current value. Is that the kind of approach you're asking for?

**Comment by RobertSzkutak** [comment]
Typically I build two CI processes : One with bootstrap and one which just deploys code. It's helpful to make the code deployment watch a git repository and deploy automatically when that repository is pushed too. However, I make the bootstrapping process a manual step. Someone more clever may be able to figure out how to make the bootstrap process kick off only when ml-config.xml is changed.

As Dave said, you could modify ml-config.xml to speed up your bootstrapping process but personally, I'd warn you off that approach. It seems like it would be more difficult to maintain properly than would be worth the effort.

**Comment by jacek-lapinski** [comment]
I was hoping that maybe there is some roxy feature I am not aware of. Thank you for your answers. I think this question can be closed.
