### ISSUE TITLE
support for roxy.jar

### ISSUE THREAD

**Issue by kgcprakash** [marklogic/roxy#716]
Hi,
ML version :: 8.0-6.1 (using the 1.7.2 version of roxy)
My company is moving towards roxy jar (from file system based roxy). so far i have encountered couple of issues.
1. the password entered in cmd prompt is visible (earlier when the password is entered it will not display like unix prompt)
2. in the earlier version we had a small xquery written to get a collection count and it was working fine. Now the output is coming along with some hex deciamal char and data type and content type. How to get rid of it? (tried few options in ruby which dint help. Any link or help would be of great help).
*****************exactly like below but spelling is bit off; sorry !! *****
--acdebefacdd
Content type: text/plain
X-Primitive : integer

      10
*****************end of return ****
(earlier i used to get only the 10)

Thanks and Regards.
kgcprakash

**Comment by dmcassel** [comment]
The second issue is because we switched Roxy to use the /v1/eval endpoint with MarkLogic 8 (and 9). That endpoint gives a multi-part response. If you send the result to the parse_multipart function defined in util.rb, you should get back just the string "10". Give that a try, and if you have trouble, please file a separate issue.

**Comment by RobertSzkutak** [comment]
Confirmed that issue 1 exists on Windows Powershell.

**Comment by kgcprakash** [comment]
Thank you very much David ( i will download the relevant jar-1.7.4, test and if issue persists - i will opened a new case).

**Comment by RobertSzkutak** [comment]
Per direct request from a major customer I will take this on as my top priority and work to resolve it.

**Comment by RobertSzkutak** [comment]
The only advice I've found on the net is to try compiling with later builds of JRuby. Will be testing out several builds as I put the release together tomorrow. (There's also advice out there recommending certain gems but I'd personally prefer to avoid adding dependencies wherever possible).

**Comment by RobertSzkutak** [comment]
@kgcprakash I've just submitted a PR with a fix which you can use to build a working JAR. We anticipate making a new release of Roxy before the end of the week at which point a JAR will be available for download.
