### ISSUE TITLE
Investigate Roxy validation

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic/roxy#726]
A comment from @dmcassel :

> I've also noticed that the validate code isn't actually getting called. setup:validate-install calls setup:validate-databases-indexes, which calls setup:validate-range-field-indexes, but nothing calls setup:validate-install (seems like setup:do-setup should).

We should investigate and ensure that validation is working properly

**Comment by grtjn** [comment]
If I recall correctly, setup:validate is used by selftest. And I also exposed it as a ./ml local validate command at some point. Not very helpful unfortunately. It stops at the first difference..

**Comment by grtjn** [comment]
Selftest invokes it here amongst others: https://github.com/marklogic/roxy/blob/master/deploy/test/test_server_config.rb#L79

That refers to this method in server config here: https://github.com/marklogic/roxy/blob/master/deploy/lib/server_config.rb#L988

I aliased it:
https://github.com/marklogic/roxy/blob/master/deploy/lib/server_config.rb#L1015

And exposed it as a public method in help at some point:
https://github.com/marklogic/roxy/blob/master/deploy/lib/Help.rb#L29

Seemed useful, but it would be nice if validate would give more thorough feedback..

**Comment by grtjn** [comment]
At quick glance, you get cascade effects, like if database doesn't exist yet, forest and property validation need to be made more robust. More messages sounds nice, but not sure it is really worth the effort..

**Comment by grtjn** [comment]
Close?

**Comment by RobertSzkutak** [comment]
Sounds good to me!
