### ISSUE TITLE
config.xqy $CTRL-EXT does not work from filesystem modules

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#736]
#### The issue

A `SVC-FILOPN` error (e.g.  `File open error: open '.../src/app/controllers/index.@ml.controller-ext': No such file or directory`) occurs when using the filesystem as the module database.

This occurs because of the line:

    declare variable $c:CTRL-EXT := ("@ml.controller-ext", $def:CTRL-EXT)[1];

When uploaded to the modules database, `@ml.controller-ext` is replaced with the revelant property value. When running on the filesystem, the `@ml.controller-ext` value is used as is.

#### Which Operating System are you using?

Windows 10

#### Which version of MarkLogic are you using?

8.0-6

#### Which version of Roxy are you using (see version.txt)?

1.7.5

**Comment by dmcassel** [comment]
Thanks for filing, I'll look into this

**Comment by dmcassel** [comment]
thanks for the PR @rhdunn. fixed in dev
