### ISSUE TITLE
Upgrading Roxy in projects still using app-modules-db causes bootstrap to fail

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#749]
app-modules-db references were removed from the project, but if you upgrade an existing project they are likely still present. Roxy will complain at bootstrap that the ml-config.xml refers to an unknown property, with a not too helpful error message like this:

```
Bootstrapping your project into MarkLogic 9 on ea4-ml1...
ERROR: note: restart required
XDMP-NOSUCHDB: xdmp:database("@ml.app-modules-db") -- No such database @ml.app-modules-db
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED
```

I recommend reinstating it in default.properties, defaulting to $modules-db, just for the purpose of legacy support..

**Comment by aajacobs** [comment]
Ran into this issue today while trying to install the data analyzer after upgrading Roxy.  Geert's suggestion worked.

**Comment by grtjn** [comment]
Fixed in dev
