### ISSUE TITLE
Upgrading Roxy clobbers default.properties environments list

### ISSUE THREAD

**Issue by masyukun** [marklogic/roxy#750]
#### The issue

I recently upgraded my Roxy deployer with the built-in upgrade command, and afterward could not deploy to "stage". 

I checked the default.properties file and saw that the environments line was replaced with the default local,dev,prod. After replacing it, things worked great again.

Steps to reproduce the problem
1. Find a project with an older version of Roxy.
2. Modify the deploy/default.properties line specifying environments with some fun additions.
3. ./ml upgrade --branch=1-7-5
4. vi deploy/default.properties
5. Search for "environment" line
6. Observe that it has reverted to the default =local,dev,prod

#### Tech Specs

- Which Operating System are you using?
  - RHEL7
- Which version of MarkLogic are you using?
  - 8.0-6.3
- Which version of Roxy are you using (see version.txt)?
  - 1.7.5

**Comment by dmcassel** [comment]
I'll refer you to [lines 5-8 of default.properties](https://github.com/marklogic/roxy/blob/master/deploy/default.properties#L5-L8). That file is not intended to be edited, for exactly this reason. default.properties is used to ensure that certain properties exist; build.properties allows you to override those values. The solution in this case is to copy the environment property to build.properties and set it to whatever you want there.
