### ISSUE TITLE
Operating System variables wiki is out of date

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#751]
https://github.com/marklogic/roxy/wiki/Using-Operating-System-Environment-Variables-in-properties is out of date, as [ServerConfig.load_properties](https://github.com/marklogic/roxy/blob/master/deploy/lib/server_config.rb#L2427) accounts for OS variables. 

Confirm that this is correct, then update wiki.

**Comment by grtjn** [comment]
The method described there is still useable, but we now have a built-in mechanism for overrides too. I'll add that..

**Comment by grtjn** [comment]
Done. I also added description of command-line argument overrides, could not find documentation about that on the wiki either..

Note: it might partially depend on #603/#787, as well as #794/#795 getting merged and closed.
