### ISSUE TITLE
use-https should control use of https for REST configuration

### ISSUE THREAD

**Issue by jkerr5** [marklogic/roxy#753]
#### Short description of the problem:

Even with the "use-https=true" property set, REST configuration does not use https unless the "ml.ssl-certificate-template" property is set to something (it can be set to anything).

This is checked here: https://github.com/marklogic/roxy/blob/master/deploy/lib/server_config.rb#L2173

This is mainly relevant where a proxy or load balancer sits in front of MarkLogic and uses https to clients but http to MarkLogic. Because there is no ssl configuration on the MarkLogic side, "ml.ssl-certificate-template" would not be set.

Shouldn't the REST use https if the "use-https=true" property is set?

#### What are the steps to reproduce the problem?

In the deploy/build.properties
1. Set "use-https=true"
2. Make sure "ml.ssl-certificate-template" is commented out 
3. Add REST configuration files in the rest-api directory
4. run ./ml <env> deploy modules

#### Tech Specs

Which Operating System are you using?
Linux

Which version of MarkLogic are you using?
8.0-6.3

Which version of Roxy are you using (see version.txt)?
1.7.3+

**Comment by grtjn** [comment]
Fixed in dev
