### ISSUE TITLE
CPF deploy config file

### ISSUE THREAD

**Issue by kosed** [marklogic/roxy#762]
#### Parametirized pipeline-config file

We are using for a project with multiple environments. We therefore have multiple $env.properties file.
We are using CPF and we also need to have different pipeline-config files but the "pipeline-config.xml" is hard coded and this is not possible.

We have made the change in server_config.rb (monkey patching as you described was also an option) by using a property variable instead of the hard coded filename.

Roxy version : 1.7.5

**Comment by dmcassel** [comment]
@kosed can you submit your changes in a PR against the dev branch? Instructions in [CONTRIBUTING.md](https://github.com/marklogic/roxy/blob/master/CONTRIBUTING.md)

**Comment by grtjn** [comment]
@kosed I think there is no need for changes. `pipeline-config.xml` can contain references to properties, and those will be replace. You can use something like ${my-prop-name}, provided you have a `my-prop-name=value` in `build-properties` or in your `{env}.properties`.

Please confirm if that works for you by closing this ticket.

**Comment by kosed** [comment]
Hello,

@dmcassel, our change is a basic one liner but I haven't been able to read the contributing info page so far.

@grtjn, Using properties is a very interesting solution for this case.
Still I think there might be a possible limitation is you actually need different pipelines/domains on different $env. May be a de/activation flag will help here. Not sure if this already exist.
What do you think ?

**Comment by grtjn** [comment]
Ah, parametrized in thát way. No, there are no options yet to enable/disable pipelines or domains with properties. Making the filename of the pipeline-config configurable makes sense. And that is probably indeed pretty much a oneliner.. :)

**Comment by grtjn** [comment]
Wasn't a oneliner after all, but not very difficult either..

Fixed in DEV..

**Comment by kosed** [comment]
Thanx @grtjn :-)
