### ISSUE TITLE
I want to use the deploy tool to capture an existing configuration

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#8]
Something like: "ml local capture", which would use the application name, servers, and ports, look at the target server, and build deploy/ml-config.xml. It would probably make sense for this to capture particular features (db settings, range indexes) rather than the whole config, so that the substitutions could remain in place.

**Comment by grtjn** [comment]
I think this progressed sufficiently to mark this as closed. Agree?

**Comment by dmcassel** [comment]
I concur. If there are enhancements to be done to the existing functionality, those can be added as new issues.
