### ISSUE TITLE
Add New Deploy Modules Flag that will deploy only New or Modifed Files

### ISSUE THREAD

**Issue by garyrusso** [marklogic/roxy#85]
Add a new flag to the deploy modules command. The new flag will only copy the new or modifed files. The logic would need to compare the last modified datetime timestamp of the destination files to the source files. If the timestamp of the source file is greater then the file is deployed. Logic would need to use UTC time for the comparisons.

**Comment by grtjn** [comment]
Resolved in #551 + #777
